
export type CountryData = {
  id: string;
  country: string;
  capital: string;
  tradeAgreement: string;
  customsInfo: string;
  customsStrictness: string;
  logisticalInfo: string;
  detailsLink: string;
  fichaPaisLink: string;
  indicadoresLink: string;
  flagCode: string;
  language: string;
  currency: string;
  culture: string;
};

export type ContinentsData = {
  [key: string]: CountryData[];
};

export const logisticData: ContinentsData = {
  'north-america': [
    { id: 'MEX', country: "México", capital: "Ciudad de México", tradeAgreement: "T-MEC", customsInfo: "https://www.gob.mx/anam", customsStrictness: "Alto, especialmente en sectores agroalimentario y farmacéutico.", logisticalInfo: "Negociación que valora las relaciones personales, pero también es directa. La jerarquía es importante.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/Ciudad-de-Mexico", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/mexico_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/mexico", flagCode: "mx", language: "Español", currency: "Peso Mexicano (MXN)", culture: "Cultura diversa y rica, con un fuerte sentido de identidad nacional y familia. La hospitalidad es clave." },
    { id: 'USA', country: "Estados Unidos", capital: "Washington D.C.", tradeAgreement: "T-MEC", customsInfo: "https://www.cbp.gov/", customsStrictness: "Muy alto. Regulaciones estrictas en alimentos (FDA), productos electrónicos (FCC) y textiles.", logisticalInfo: "Negociación muy directa, rápida y enfocada en resultados y datos. La puntualidad es crucial.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/Washington-DC", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/estadosunidos_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/estados-unidos", flagCode: "us", language: "Inglés", currency: "Dólar Estadounidense (USD)", culture: "Individualista y orientada a objetivos. La comunicación es directa y se valora la eficiencia." },
    { id: 'CAN', country: "Canadá", capital: "Ottawa", tradeAgreement: "T-MEC", customsInfo: "https://www.cbsa-asfc.gc.ca/", customsStrictness: "Alto, con requisitos bilingües (inglés/francés) para etiquetado en muchos productos.", logisticalInfo: "Negociación directa, pragmática y basada en hechos. Son cooperativos y buscan el beneficio mutuo.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/Ottawa", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/canada_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/canada", flagCode: "ca", language: "Inglés, Francés", currency: "Dólar Canadiense (CAD)", culture: "Multicultural y reservada. Se valora la cortesía, la puntualidad y el respeto por el espacio personal." },
    { id: 'PAN', country: "Panamá", capital: "Ciudad de Pánama", tradeAgreement: "No hay en snippet", customsInfo: "https://www.ana.gob.pa/", customsStrictness: "Medio. Eficiente por el canal, pero con burocracia para ciertos trámites.", logisticalInfo: "Relacional y pragmática. Valoran la puntualidad y las relaciones a largo plazo.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/Ciudad-de-Panama", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/panama_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/panama", flagCode: "pa", language: "Español", currency: "Balboa (PAB), Dólar Estadounidense (USD)", culture: "Cultura de servicio orientada al comercio internacional. La amabilidad es importante en los negocios." },
    { id: 'BLZ', country: "Belice", capital: "Belmopán", tradeAgreement: "No tienen", customsInfo: "https://www.customs.gov.bz/", customsStrictness: "Bajo-Medio. Proceso generalmente ágil para bienes comunes.", logisticalInfo: "Negociación informal y directa. El inglés es el idioma oficial.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/Belmopan", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/belice_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/belice", flagCode: "bz", language: "Inglés", currency: "Dólar Beliceño (BZD)", culture: "Cultura relajada y amigable, con influencias caribeñas y mayas." },
    { id: 'CRI', country: "Costa Rica", capital: "San José", tradeAgreement: "Si tienen", customsInfo: "https://www.hacienda.go.cr/aduanas/pasocanoas.html", customsStrictness: "Medio-Alto. Foco en regulaciones ambientales y sanitarias.", logisticalInfo: "Valoran la cortesía y la sostenibilidad. Estilo educado y menos directo.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/San-Jose,Costa-Rica", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/costa%20rica_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/costa-rica", flagCode: "cr", language: "Español", currency: "Colón Costarricense (CRC)", culture: "Conocida por su lema 'Pura Vida', la cultura es pacífica y valora la naturaleza y la educación." },
    { id: 'SLV', country: "El Salvador", capital: "San Salvador", tradeAgreement: "Si tienen", customsInfo: "https://sitio.aduana.gob.sv/", customsStrictness: "Alto en seguridad y control de mercancías ilícitas.", logisticalInfo: "Negociación directa y orientada a resultados. La seguridad es un tema importante.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/San-Salvador", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/elsalvador_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/el-salvador", flagCode: "sv", language: "Español", currency: "Dólar Estadounidense (USD)", culture: "Trabajadora y resiliente. La familia y la religión son pilares importantes." },
    { id: 'GTM', country: "Guatemala", capital: "Ciudad de Guatemala", tradeAgreement: "Si tienen", customsInfo: "https://portal.sat.gob.gt/portal/aduanas/", customsStrictness: "Variable. Puede haber retrasos y se requiere documentación precisa.", logisticalInfo: "Combinación de formalidad y relaciones personales. La jerarquía es respetada.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/Ciudad-de-Guatemala", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/guatemala_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/guatemala", flagCode: "gt", language: "Español", currency: "Quetzal (GTQ)", culture: "Rica herencia maya. La familia es central y se valora el respeto a los mayores." },
    { id: 'HND', country: "Honduras", capital: "Tegucigalpa", tradeAgreement: "Si tienen", customsInfo: "https://www.aduanas.gob.hn/", customsStrictness: "Medio. Procesos en modernización, pero aún pueden ser complejos.", logisticalInfo: "Estilo de negociación relajado pero se valora el compromiso.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/Tegucigalpa", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/honduras_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/honduras", flagCode: "hn", language: "Español", currency: "Lempira (HNL)", culture: "Cálida y hospitalaria. La familia extendida y la comunidad son fundamentales." },
  ],
  'south-america': [
    { id: 'ARG', country: 'Argentina', capital: 'Buenos Aires', tradeAgreement: 'MERCOSUR', customsInfo: 'https://www.afip.gob.ar/aduana/', customsStrictness: "Alto. Restricciones cambiarias y licencias no automáticas afectan la importación.", logisticalInfo: "Formal en apertura, buscan vínculo personal; les gusta debatir con intensidad.", detailsLink: "https://es.distance.to/Lima,PER/Paso-De-Jama,Coranzuli,Susques,Jujuy,ARG/Buenos-Aires,Ciudad-Aut%C3%B3noma-de-Buenos-Aires,ARG", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/argentina_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/argentina", flagCode: "ar", language: "Español", currency: "Peso Argentino (ARS)", culture: "Fuerte influencia europea. Se valora la socialización, la pasión por el fútbol y la buena comida." },
    { id: 'BOL', country: "Bolivia", capital: "La Paz", tradeAgreement: "MERCOSUR", customsInfo: "https://www.aduana.gob.bo/", customsStrictness: "Medio-Alto. Procesos burocráticos pueden ser lentos. Sensible en sector agrícola.", logisticalInfo: "Negociación formal, protocolar, orientada a la jerarquía.", detailsLink: "https://es.distance.to/Lima,PER/La-Paz,BOL", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/bolivia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/bolivia", flagCode: "bo", language: "Español, Quechua, Aymara", currency: "Boliviano (BOB)", culture: "Plurinacional, con fuerte presencia de culturas indígenas. La familia y la comunidad son centrales." },
    { id: 'PRY', country: "Paraguay", capital: "Asunción", tradeAgreement: "MERCOSUR", customsInfo: "https://www.aduana.gov.py/", customsStrictness: "Medio. Especialmente en la frontera con Brasil y Argentina por contrabando.", logisticalInfo: "Formal pero flexible; se valora la relación personal.", detailsLink: "https://es.distance.to/Lima,PER/Asuncion,PRY", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/paraguay_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/paraguay", flagCode: "py", language: "Español, Guaraní", currency: "Guaraní (PYG)", culture: "Bilingüe y hospitalaria. El 'tereré' es una costumbre social importante." },
    { id: 'URY', country: "Uruguay", capital: "Montevideo", tradeAgreement: "MERCOSUR", customsInfo: "https://www.aduanas.gub.uy/", customsStrictness: "Medio. Considerada una de las aduanas más eficientes de la región.", logisticalInfo: "Formal, sobrio y pragmático; ser claro y confiable.", detailsLink: "https://es.distance.to/Lima,PER/Montevideo,URY", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/uruguay_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/uruguay", flagCode: "uy", language: "Español", currency: "Peso Uruguayo (UYU)", culture: "Similar a la argentina, con gran afición por el mate y el asado. Estable y secular." },
    { id: 'VEN', country: "Venezuela", capital: "Caracas", tradeAgreement: "TLC PERU - VENEZUELA", customsInfo: "http://declaraciones.seniat.gob.ve/", customsStrictness: "Muy alto y complejo debido a la situación política y económica.", logisticalInfo: "Relacional, centrada en la confianza; la puntualidad es flexible.", detailsLink: "https://es.distance.to/Lima,PER/Caracas,VEN", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/venezuela_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/venezuela--republica-bolivariana-de", flagCode: "ve", language: "Español", currency: "Bolívar Digital (VED)", culture: "Alegre y extrovertida. La música, como el joropo, y la familia son muy importantes." },
    { id: 'BRA', country: "Brasil", capital: "Brasilia", tradeAgreement: "MERCOSUR", customsInfo: "http://www.receita.fazenda.gov.br/", customsStrictness: "Muy alto. Burocracia compleja y sistema tributario denso.", logisticalInfo: "Relacional y entusiasta. La paciencia es clave, las decisiones pueden tomar tiempo.", detailsLink: "https://es.distance.to/Lima,PER/Brasilia,BRA", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/brasil_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/brasil", flagCode: "br", language: "Portugués", currency: "Real Brasileño (BRL)", culture: "Vibrante y diversa. El carnaval, el fútbol y la música (samba, bossa nova) son mundialmente famosos." },
    { id: 'CHL', country: "Chile", capital: "Santiago", tradeAgreement: "Alianza del Pacífico", customsInfo: "https://www.aduana.cl/", customsStrictness: "Alto. Muy eficientes y regulados, especialmente en productos agrícolas (SAG).", logisticalInfo: "Directa, profesional y formal. Valoran la eficiencia y la preparación.", detailsLink: "https://es.distance.to/Lima,PER/Santiago,CHL", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/chile_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/chile", flagCode: "cl", language: "Español", currency: "Peso Chileno (CLP)", culture: "Más reservada y formal que otros países de la región. Valoran la estabilidad y el orden." },
  ],
  'europe': [
    { id: 'ALB', country: "Albania", capital: "Tirana", tradeAgreement: "No tiene (Miembro AELC)", customsInfo: "https://www.dogana.gov.al/", customsStrictness: "Medio. En proceso de alineación con estándares de la UE.", logisticalInfo: "La negociación puede ser lenta, se valora la relación personal.", detailsLink: "https://es.distance.to/Países-Bajos/Tirana,ALB", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/ALBANIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/albania", flagCode: "al", language: "Albanés", currency: "Lek (ALL)", culture: "Hospitalaria y basada en códigos de honor tradicionales. La familia es fundamental." },
    { id: 'SWE', country: "Suecia", capital: "Estocolmo", tradeAgreement: "TLC UE-Perú (Miembro UE)", customsInfo: "https://www.tullverket.se/", customsStrictness: "Muy Alto. Cumplimiento estricto de normativas medioambientales y de seguridad de la UE.", logisticalInfo: "Pragmática, basada en datos. Puntualidad estricta y comunicación directa.", detailsLink: "https://es.distance.to/Países-Bajos/Stockholm,SWE", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/SUECIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/suecia", flagCode: "se", language: "Sueco", currency: "Corona Sueca (SEK)", culture: "Igualitaria y progresista. Se valora el consenso ('lagom') y la naturaleza." },
    { id: 'CHE', country: "Suiza", capital: "Berna", tradeAgreement: "TLC AELC-Perú (Miembro AELC)", customsInfo: "https://www.bazg.admin.ch/", customsStrictness: "Muy Alto. Precisión y calidad son claves, especialmente en relojería, farmacéuticos y alimentos.", logisticalInfo: "Formal, bien preparada y detallista. La calidad y precisión son primordiales.", detailsLink: "https://es.distance.to/Países-Bajos/Bern,CHE", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/SUIZA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/suiza", flagCode: "ch", language: "Alemán, Francés, Italiano, Romanche", currency: "Franco Suizo (CHF)", culture: "Precisa, puntual y privada. Se valora la calidad, la eficiencia y el respeto por las normas." },
    { id: 'TUR', country: "Turquía", capital: "Ankara", tradeAgreement: "Acuerdo de la Union Aduanera -UE (Miembro AELC)", customsInfo: "https://www.ticaret.gov.tr/gumruk-islemleri", customsStrictness: "Alto. Regulaciones complejas y cambiantes. Sensible en textiles y agricultura.", logisticalInfo: "Relacional y hospitalaria, pero también dura en la negociación de precios.", detailsLink: "https://es.distance.to/Países-Bajos/Ankara,TUR", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/turquia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/turquia", flagCode: "tr", language: "Turco", currency: "Lira Turca (TRY)", culture: "Puente entre Oriente y Occidente. Hospitalaria y familiar. El regateo es común en los mercados." },
    { id: 'DEU', country: "Alemania", capital: "Berlín", tradeAgreement: "TLC UE-Perú (Miembro UE)", customsInfo: "https://www.zoll.de/", customsStrictness: "Muy Alto. Famosos por su eficiencia y estricto cumplimiento de las normativas de la UE.", logisticalInfo: "Directa, formal y muy estructurada. Los datos y hechos son cruciales.", detailsLink: "https://es.distance.to/Países-Bajos/Berlin,DEU", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/alemania_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/alemania", flagCode: "de", language: "Alemán", currency: "Euro (EUR)", culture: "Organizada, puntual y eficiente. La separación entre la vida privada y profesional es marcada." },
    { id: 'FRA', country: "Francia", capital: "París", tradeAgreement: "TLC UE-Perú (Miembro UE)", customsInfo: "https://www.douane.gouv.fr/", customsStrictness: "Alto. Proteccionistas en sectores como agricultura y cultura. Normas de etiquetado estrictas.", logisticalInfo: "Formal y analítica. El idioma francés es muy valorado.", detailsLink: "https://es.distance.to/Países-Bajos/Paris,FRA", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/francia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/francia", flagCode: "fr", language: "Francés", currency: "Euro (EUR)", culture: "Sofisticada y orgullosa de su herencia. La gastronomía, el arte y la moda son pilares culturales." },
  ],
  'asia': [
    { id: 'CHN', country: 'China', capital: 'Pekín', tradeAgreement: 'Ninguno específico en snippet', customsInfo: 'http://english.customs.gov.cn/', customsStrictness: 'Muy Alto. Las regulaciones pueden ser complejas y cambiar rápidamente. Censura y licencias son comunes.', logisticalInfo: 'Muy formal, estructurada... Los chinos evitan la confrontación.', detailsLink: 'https://es.distance.to/Pekín,CHN/Pekín,CHN', fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/china_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/china", flagCode: "cn", language: "Chino Mandarín", currency: "Yuan (CNY)", culture: "Colectivista y jerárquica. El 'guanxi' (red de contactos) y el respeto a la autoridad son vitales." },
    { id: 'UZB', country: "Uzbekistán", capital: "Taskent", tradeAgreement: "Sin FTA", customsInfo: "https://customs.uz/en/", customsStrictness: "Alto. Procesos burocráticos heredados de la era soviética.", logisticalInfo: "Formal, jerárquica y protocolar; se respeta mucho la autoridad.", detailsLink: "https://es.distance.to/Pekín,CHN/Taskent,UZB", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/uzbekistan_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/uzbekistan", flagCode: "uz", language: "Uzbeko", currency: "Som Uzbeko (UZS)", culture: "Influenciada por la Ruta de la Seda. Hospitalaria y comunitaria. El respeto a los mayores es primordial." },
    { id: 'VNM', country: "Vietnam", capital: "Hanói", tradeAgreement: "ASEAN - China - ASEAN FTA + RCEP", customsInfo: "https://www.customs.gov.vn/index.jsp?pageId=23&groupdId=2&language=en", customsStrictness: "Alto. Las regulaciones son complejas y la interpretación puede variar.", logisticalInfo: "Formal pero basada en relaciones personales; evitan decir “no” directamente.", detailsLink: "https://es.distance.to/Pekín,CHN/Hanoi,VNM", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/vietnam_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/vietnam", flagCode: "vn", language: "Vietnamita", currency: "Dong (VND)", culture: "Respetuosa de la jerarquía y la edad. La cara ('mặt') y el colectivismo son conceptos clave." },
    { id: 'IND', country: "India", capital: "Nueva Delhi", tradeAgreement: "En negociación", customsInfo: "https://www.cbic.gov.in/", customsStrictness: "Muy Alto. Conocida por su burocracia ('Red Tape') y regulaciones complejas.", logisticalInfo: "Jerárquica y relacional. La negociación puede ser larga y detallada.", detailsLink: "https://es.distance.to/Pekín,CHN/New-Delhi,IND", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/india_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/india", flagCode: "in", language: "Hindi, Inglés", currency: "Rupia India (INR)", culture: "Extremadamente diversa en religión, idioma y etnia. La familia y la jerarquía son muy importantes." },
  ],
  'africa': [
    { id: 'DZA', country: "Argelia", capital: "Argel", tradeAgreement: "AfCFTA", customsInfo: "https://douane.gov.dz/?lang=fr", customsStrictness: "Alto. Burocracia significativa y requisitos de documentación en francés.", logisticalInfo: "Negociación formal y jerárquica, orientada a resultados.", detailsLink: "https://es.distance.to/Johannesburgo,ZAF/Algiers,DZA", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/argelia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/argelia", flagCode: "dz", language: "Árabe, Bereber", currency: "Dinar Argelino (DZD)", culture: "Conservadora y patriarcal. La religión (Islam) y la familia son los pilares de la sociedad." },
    { id: 'TUN', country: "Túnez", capital: "Túnez", tradeAgreement: "AfCFTA", customsInfo: "http://www.douane.gov.tn/", customsStrictness: "Medio-Alto. Proceso de modernización en curso. Sectores como el textil son sensibles.", logisticalInfo: "Se valora la cortesía y la construcción de relaciones.", detailsLink: "https://es.distance.to/Johannesburgo,ZAF/Tunis,TUN", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/tunez_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/tunez", flagCode: "tn", language: "Árabe", currency: "Dinar Tunecino (TND)", culture: "Considerada una de las más liberales del mundo árabe. Hospitalaria y orientada a la familia." },
    { id: 'UGA', country: "Uganda", capital: "Kampala", tradeAgreement: "AfCFTA", customsInfo: "https://ura.go.ug/en/", customsStrictness: "Medio. La corrupción puede ser un desafío. Documentación clara es vital.", logisticalInfo: "Negociación abierta, se valora la honestidad.", detailsLink: "https://es.distance.to/Johannesburgo,ZAF/Kampala,UGA", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/uganda_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/uganda", flagCode: "ug", language: "Inglés, Suajili", currency: "Chelín Ugandés (UGX)", culture: "Étnicamente diversa. La comunidad y la familia extendida son muy importantes." },
    { id: 'ZMB', country: "Zambia", capital: "Lusaka", tradeAgreement: "SADC; AfCFTA", customsInfo: "https://www.zra.org.zm/", customsStrictness: "Medio. Regulaciones mineras y agrícolas son particularmente importantes.", logisticalInfo: "Negociación formal, basada en acuerdos firmes.", detailsLink: "https://es.distance.to/Johannesburgo,ZAF/Lusaka,ZMB", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/zambia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/zambia", flagCode: "zm", language: "Inglés", currency: "Kwacha Zambiano (ZMW)", culture: "Pacífica y amigable. El respeto a los mayores es un valor fundamental." },
    { id: 'SLE', country: "Sierra Leona", capital: "Freetown", tradeAgreement: "AfCFTA", customsInfo: "https://www.nra.gov.sl/", customsStrictness: "Bajo-Medio. Desafíos logísticos y de infraestructura pueden ser más problemáticos que las regulaciones.", logisticalInfo: "Negociación relacional, se prioriza la confianza.", detailsLink: "https://es.distance.to/Johannesburgo,ZAF/Freetown,SLE", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/sierraleona_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/sierra-leona", flagCode: "sl", language: "Inglés", currency: "Leone (SLL)", culture: "Fuerte sentido de comunidad. La religión y las sociedades secretas juegan un papel importante." },
    { id: 'NGA', country: "Nigeria", capital: "Abuya", tradeAgreement: "AfCFTA", customsInfo: "https://customs.gov.ng/", customsStrictness: "Alto. Regulaciones complejas y riesgo de corrupción. El sector petrolero tiene sus propias reglas.", logisticalInfo: "Enfocada en el precio y las relaciones personales. Puede ser una negociación dura.", detailsLink: "https://es.distance.to/Johannesburgo,ZAF/Abuja,NGA", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/nigeria_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/nigeria", flagCode: "ng", language: "Inglés", currency: "Naira (NGN)", culture: "Muy diversa étnicamente. Emprendedora y extrovertida. El respeto a la edad y la jerarquía es clave." },
  ],
  'oceania': [
    { id: 'AUS_mel', country: "Australia", capital: "Melbourne", tradeAgreement: "ALC Perú - Australia", customsInfo: "https://www.abf.gov.au/", customsStrictness: "Muy Alto. Bioseguridad es extremadamente estricta (agricultura, alimentos).", logisticalInfo: "Formal, estructurada; muy estricta puntualidad.", detailsLink: "https://es.distance.to/Sídney/Melbourne", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/australia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/australia", flagCode: "au", language: "Inglés", currency: "Dólar Australiano (AUD)", culture: "Relajada, informal y directa. Se valora el igualitarismo y el humor autocrítico." },
    { id: 'AUS_syd', country: "Australia", capital: "Sídney", tradeAgreement: "ALC Perú - Australia", customsInfo: "https://www.abf.gov.au/", customsStrictness: "Muy Alto. Bioseguridad es extremadamente estricta (agricultura, alimentos).", logisticalInfo: "Práctica y enfocada en resultados; valoran la rapidez.", detailsLink: "https://es.distance.to/Sídney/Sídney", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/australia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/australia", flagCode: "au", language: "Inglés", currency: "Dólar Australiano (AUD)", culture: "Relajada, informal y directa. Se valora el igualitarismo y el humor autocrítico." },
  ],
  'otros': [
    // Gran Bretaña
    ...["Manchester", "Birmingham", "Liverpool", "Leeds", "Bristol", "Oxford", "Cambridge", "Sheffield", "Newcastle upon Tyne", "Nottingham", "Southampton", "Brighton", "Bath", "Cardiff", "Milton Keynes", "York", "Sunderland", "Londres"].map(city => ({ id: `gbr-${city.toLowerCase().replace(/ /g, '-')}`, country: "Gran Bretaña", capital: city, tradeAgreement: "TLC Perú-Reino Unido", customsInfo: "https://www.gov.uk/government/organisations/hm-revenue-customs", customsStrictness: "Alto", logisticalInfo: "Profesional y puntual.", detailsLink: `https://es.distance.to/Londres/${city.replace(/ /g, '-')}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "gb", language: "Inglés", currency: "Libra Esterlina (GBP)", culture: "Reservada y educada." })),
    
    // Escocia
    ...["Glasgow", "Aberdeen", "Dundee", "Inverness", "Stirling", "Perth", "Elgin"].map(city => ({ id: `sct-${city.toLowerCase().replace(/ /g, '-')}`, country: "Escocia", capital: city, tradeAgreement: "TLC Perú-Reino Unido", customsInfo: "https://www.gov.uk/government/organisations/hm-revenue-customs", customsStrictness: "Alto", logisticalInfo: "Pragmáticos y directos.", detailsLink: `https://es.distance.to/Edimburgo/${city.replace(/ /g, '-')}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "gb-sct", language: "Inglés, Gaélico", currency: "Libra Esterlina (GBP)", culture: "Fuerte identidad cultural." })),

    // Malta
    ...["Vittoriosa", "Cospicua", "Senglea"].map(city => ({ id: `mlt-${city.toLowerCase()}`, country: "Malta", capital: city, tradeAgreement: "TLC UE-Perú", customsInfo: "https://customs.gov.mt/", customsStrictness: "Medio", logisticalInfo: "Relacional y flexible.", detailsLink: `https://es.distance.to/Valeta/${city}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "mt", language: "Maltés, Inglés", currency: "Euro (EUR)", culture: "Influencia mediterránea y británica." })),

    // Irlanda
    ...["Cork", "Galway", "Límerick", "Dundalk", "Waterford", "Drogheda", "Navan", "Bray"].map(city => ({ id: `irl-${city.toLowerCase()}`, country: "Irlanda", capital: city, tradeAgreement: "TLC UE-Perú", customsInfo: "https://www.revenue.ie/en/customs-traders-and-agents/index.aspx", customsStrictness: "Alto (normas UE)", logisticalInfo: "Amigable y directa.", detailsLink: `https://es.distance.to/Dublin/${city}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "ie", language: "Irlandés, Inglés", currency: "Euro (EUR)", culture: "Acogedora y social." })),

    // Japón
    ...["Osaka", "Kyoto", "Fukuoka", "Kobe", "Nagoya", "Hiroshima", "Sendai", "Nagasaki", "Chiba", "Kumamoto", "Saitama", "Shizuoka", "Nagano", "Yokohama", "Nara", "Utsunomiya", "Kanagawa", "Kanazawa", "Hakone", "Nikkō", "Matsuyama", "Okayama"].map(city => ({ id: `jpn-${city.toLowerCase()}`, country: "Japon", capital: city, tradeAgreement: "CPTPP", customsInfo: "https://www.customs.go.jp/english/", customsStrictness: "Muy alto", logisticalInfo: "Extremadamente formal y puntual.", detailsLink: `https://es.distance.to/Tokio/${city}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "jp", language: "Japonés", currency: "Yen (JPY)", culture: "Respeto por la jerarquía y la etiqueta." })),

    // Corea del Sur
    ...["Busan", "Daegu", "Incheon", "Daejeon", "Ulsan", "Gwangjung", "Pyeongtaek"].map(city => ({ id: `kor-${city.toLowerCase()}`, country: "Corea del Sur", capital: city, tradeAgreement: "TLC Perú-Corea", customsInfo: "https://www.customs.go.kr/eng/main.do", customsStrictness: "Alto", logisticalInfo: "Rápida y relacional.", detailsLink: `https://es.distance.to/Seul/${city}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "kr", language: "Coreano", currency: "Won (KRW)", culture: "Dinámica y tecnológica." })),

    // Nueva Zelanda (Isla Norte)
    ...["Auckland", "Hamilton", "Tauranga", "Napier", "Palmerston North", "Rotorua", "Whanganui", "Gisborne", "Taupō", "Whangārei"].map(city => ({ id: `nzn-${city.toLowerCase().replace('ā','a')}`, country: "Nueva Zelanda (Isla Norte)", capital: city, tradeAgreement: "CPTPP", customsInfo: "https://www.customs.govt.nz/", customsStrictness: "Muy Alto (Bioseguridad)", logisticalInfo: "Directa y pragmática.", detailsLink: `https://es.distance.to/Wellington/${city.replace('ā','a')}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "nz", language: "Inglés, Maorí", currency: "Dólar Neozelandés (NZD)", culture: "Relajada y amante de la naturaleza." })),

    // Nueva Zelanda (Isla Sur)
    ...["Picton", "Kaikoura", "Blenheim", "Greymouth", "Queenstown", "Timaru", "Dunedin", "Invercargill"].map(city => ({ id: `nzs-${city.toLowerCase()}`, country: "Nueva Zelanda (Isla Sur)", capital: city, tradeAgreement: "CPTPP", customsInfo: "https://www.customs.govt.nz/", customsStrictness: "Muy Alto (Bioseguridad)", logisticalInfo: "Directa y pragmática.", detailsLink: `https://es.distance.to/Christchurch/${city}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "nz", language: "Inglés, Maorí", currency: "Dólar Neozelandés (NZD)", culture: "Aventura y paisajes espectaculares." })),

    // Bahréin
    ...["Al Muharraq", "Riffa", "Madinat Hamad", "Madinat 'Isa", "Sitra", "Jidhafs"].map(city => ({ id: `bhr-${city.toLowerCase().replace(/ /g, '-').replace(/'/g, '')}`, country: "Bahréin", capital: city, tradeAgreement: "No específico", customsInfo: "https://www.bahraincustoms.gov.bh/", customsStrictness: "Medio", logisticalInfo: "Relacional y de negocios.", detailsLink: `https://es.distance.to/Manama/${city.replace(/ /g, '-')}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "bh", language: "Árabe", currency: "Dinar Bahreiní (BHD)", culture: "Centro financiero y comercial." })),

    // Chipre
    ...["Limasol", "Larnaca", "Pafos", "Famagusta", "Kyrenia", "Ayia Napa", "Paralimni"].map(city => ({ id: `cyp-${city.toLowerCase().replace(/ /g, '-')}`, country: "Chipre", capital: city, tradeAgreement: "TLC UE-Perú", customsInfo: "https://www.mof.gov.cy/mof/customs/customs.nsf/index_en/index_en", customsStrictness: "Alto (normas UE)", logisticalInfo: "Flexible y orientado a relaciones.", detailsLink: `https://es.distance.to/Nicosia/${city.replace(/ /g, '-')}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "cy", language: "Griego, Turco", currency: "Euro (EUR)", culture: "Cruce de culturas europea y de Oriente Medio." })),
    
    // Indonesia
    ...["Bandung", "Bekasi", "Bogor", "Depok", "Malang", "Semarang", "Surabaya", "Yogyakarta", "Cirebon", "Sukabumi", "Tasikmalaya"].map(city => ({ id: `idn-${city.toLowerCase()}`, country: "Indonesia", capital: city, tradeAgreement: "En negociación", customsInfo: "https://www.beacukai.go.id/", customsStrictness: "Alto", logisticalInfo: "Indirecta y relacional.", detailsLink: `https://es.distance.to/Yakarta/${city}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "id", language: "Indonesio", currency: "Rupia Indonesia (IDR)", culture: "Extremadamente diversa." })),
  ],
};
