export type CountryData = {
  id: string;
  country: string;
  capital: string;
  tradeAgreement: string;
  customsInfo: string;
  logisticalInfo: string;
  detailsLink: string;
  fichaPaisLink: string;
  indicadoresLink: string;
  flagCode: string;
};

export type ContinentsData = {
  [key: string]: CountryData[];
};

export const logisticData: ContinentsData = {
  'north-america': [
    { id: 'MEX', country: "México", capital: "Ciudad de México", tradeAgreement: "T-MEC", customsInfo: "https://www.gob.mx/anam", logisticalInfo: "Negociación que valora las relaciones personales, pero también es directa. La jerarquía es importante.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/Ciudad-de-Mexico", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/mexico_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/mexico", flagCode: "mx" },
    { id: 'USA', country: "Estados Unidos", capital: "Washington D.C.", tradeAgreement: "T-MEC", customsInfo: "https://www.cbp.gov/", logisticalInfo: "Negociación muy directa, rápida y enfocada en resultados y datos. La puntualidad es crucial.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/Washington-DC", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/estadosunidos_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/estados-unidos", flagCode: "us" },
    { id: 'CAN', country: "Canadá", capital: "Ottawa", tradeAgreement: "T-MEC", customsInfo: "https://www.cbsa-asfc.gc.ca/", logisticalInfo: "Negociación directa, pragmática y basada en hechos. Son cooperativos y buscan el beneficio mutuo.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/Ottawa", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/canada_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/canada", flagCode: "ca" },
    { id: 'PAN', country: "Panamá", capital: "Ciudad de Pánama", tradeAgreement: "No hay en snippet", customsInfo: "https://www.ana.gob.pa/", logisticalInfo: "Relacional y pragmática. Valoran la puntualidad y las relaciones a largo plazo.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/Ciudad-de-Panama", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/panama_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/panama", flagCode: "pa" },
    { id: 'BLZ', country: "Belice", capital: "Belmopán", tradeAgreement: "No tienen", customsInfo: "https://www.customs.gov.bz/", logisticalInfo: "Negociación informal y directa. El inglés es el idioma oficial.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/Belmopan", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/belice_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/belice", flagCode: "bz" },
    { id: 'CRI', country: "Costa Rica", capital: "San José", tradeAgreement: "Si tienen", customsInfo: "https://www.hacienda.go.cr/aduanas/pasocanoas.html", logisticalInfo: "Valoran la cortesía y la sostenibilidad. Estilo educado y menos directo.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/San-Jose,Costa-Rica", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/costa%20rica_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/costa-rica", flagCode: "cr" },
    { id: 'SLV', country: "El Salvador", capital: "San Salvador", tradeAgreement: "Si tienen", customsInfo: "https://sitio.aduana.gob.sv/", logisticalInfo: "Negociación directa y orientada a resultados. La seguridad es un tema importante.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/San-Salvador", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/elsalvador_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/el-salvador", flagCode: "sv" },
    { id: 'GTM', country: "Guatemala", capital: "Ciudad de Guatemala", tradeAgreement: "Si tienen", customsInfo: "https://portal.sat.gob.gt/portal/aduanas/", logisticalInfo: "Combinación de formalidad y relaciones personales. La jerarquía es respetada.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/Ciudad-de-Guatemala", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/guatemala_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/guatemala", flagCode: "gt" },
    { id: 'HND', country: "Honduras", capital: "Tegucigalpa", tradeAgreement: "Si tienen", customsInfo: "https://www.aduanas.gob.hn/", logisticalInfo: "Estilo de negociación relajado pero se valora el compromiso.", detailsLink: "https://es.distance.to/Ciudad-de-Panama/Tegucigalpa", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/honduras_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/honduras", flagCode: "hn" },
  ],
  'south-america': [
    { id: 'ARG', country: 'Argentina', capital: 'Buenos Aires', tradeAgreement: 'MERCOSUR', customsInfo: 'https://www.afip.gob.ar/aduana/', logisticalInfo: "Formal en apertura, buscan vínculo personal; les gusta debatir con intensidad.", detailsLink: "https://es.distance.to/Lima,PER/Paso-De-Jama,Coranzuli,Susques,Jujuy,ARG/Buenos-Aires,Ciudad-Aut%C3%B3noma-de-Buenos-Aires,ARG", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/argentina_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/argentina", flagCode: "ar" },
    { id: 'BOL', country: "Bolivia", capital: "La Paz", tradeAgreement: "MERCOSUR", customsInfo: "https://www.aduana.gob.bo/", logisticalInfo: "Negociación formal, protocolar, orientada a la jerarquía.", detailsLink: "https://es.distance.to/Lima,PER/La-Paz,BOL", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/bolivia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/bolivia", flagCode: "bo" },
    { id: 'PRY', country: "Paraguay", capital: "Asunción", tradeAgreement: "MERCOSUR", customsInfo: "https://www.aduana.gov.py/", logisticalInfo: "Formal pero flexible; se valora la relación personal.", detailsLink: "https://es.distance.to/Lima,PER/Asuncion,PRY", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/paraguay_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/paraguay", flagCode: "py" },
    { id: 'URY', country: "Uruguay", capital: "Montevideo", tradeAgreement: "MERCOSUR", customsInfo: "https://www.aduanas.gub.uy/", logisticalInfo: "Formal, sobrio y pragmático; ser claro y confiable.", detailsLink: "https://es.distance.to/Lima,PER/Montevideo,URY", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/uruguay_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/uruguay", flagCode: "uy" },
    { id: 'VEN', country: "Venezuela", capital: "Caracas", tradeAgreement: "TLC PERU - VENEZUELA", customsInfo: "http://declaraciones.seniat.gob.ve/", logisticalInfo: "Relacional, centrada en la confianza; la puntualidad es flexible.", detailsLink: "https://es.distance.to/Lima,PER/Caracas,VEN", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/venezuela_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/venezuela--republica-bolivariana-de", flagCode: "ve" },
    { id: 'BRA', country: "Brasil", capital: "Brasilia", tradeAgreement: "MERCOSUR", customsInfo: "http://www.receita.fazenda.gov.br/", logisticalInfo: "Relacional y entusiasta. La paciencia es clave, las decisiones pueden tomar tiempo.", detailsLink: "https://es.distance.to/Lima,PER/Brasilia,BRA", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/brasil_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/brasil", flagCode: "br" },
    { id: 'CHL', country: "Chile", capital: "Santiago", tradeAgreement: "Alianza del Pacífico", customsInfo: "https://www.aduana.cl/", logisticalInfo: "Directa, profesional y formal. Valoran la eficiencia y la preparación.", detailsLink: "https://es.distance.to/Lima,PER/Santiago,CHL", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/chile_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/chile", flagCode: "cl" },
  ],
  'europe': [
    { id: 'ALB', country: "Albania", capital: "Tirana", tradeAgreement: "No tiene (Miembro AELC)", customsInfo: "https://www.dogana.gov.al/", logisticalInfo: "La negociación puede ser lenta, se valora la relación personal.", detailsLink: "https://es.distance.to/Amsterdam,NLD/Tirana,ALB", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/ALBANIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/albania", flagCode: "al" },
    { id: 'SWE', country: "Suecia", capital: "Estocolmo", tradeAgreement: "TLC UE-Perú (Miembro UE)", customsInfo: "https://www.tullverket.se/", logisticalInfo: "Pragmática, basada en datos. Puntualidad estricta y comunicación directa.", detailsLink: "https://es.distance.to/Amsterdam,NLD/Stockholm,SWE", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/SUECIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/suecia", flagCode: "se" },
    { id: 'CHE', country: "Suiza", capital: "Berna", tradeAgreement: "TLC AELC-Perú (Miembro AELC)", customsInfo: "https://www.bazg.admin.ch/", logisticalInfo: "Formal, bien preparada y detallista. La calidad y precisión son primordiales.", detailsLink: "https://es.distance.to/Amsterdam,NLD/Bern,CHE", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/SUIZA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/suiza", flagCode: "ch" },
    { id: 'TUR', country: "Turquía", capital: "Ankara", tradeAgreement: "Acuerdo de la Union Aduanera -UE (Miembro AELC)", customsInfo: "https://www.ticaret.gov.tr/gumruk-islemleri", logisticalInfo: "Relacional y hospitalaria, pero también dura en la negociación de precios.", detailsLink: "https://es.distance.to/Amsterdam,NLD/Ankara,TUR", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/turquia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/turquia", flagCode: "tr" },
    { id: 'DEU', country: "Alemania", capital: "Berlín", tradeAgreement: "TLC UE-Perú (Miembro UE)", customsInfo: "https://www.zoll.de/", logisticalInfo: "Directa, formal y muy estructurada. Los datos y hechos son cruciales.", detailsLink: "https://es.distance.to/Amsterdam,NLD/Berlin,DEU", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/alemania_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/alemania", flagCode: "de" },
    { id: 'FRA', country: "Francia", capital: "París", tradeAgreement: "TLC UE-Perú (Miembro UE)", customsInfo: "https://www.douane.gouv.fr/", logisticalInfo: "Formal y analítica. El idioma francés es muy valorado.", detailsLink: "https://es.distance.to/Amsterdam,NLD/Paris,FRA", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/francia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/francia", flagCode: "fr" },
  ],
  'asia': [
    { id: 'CHN', country: 'China', capital: 'Pekín', tradeAgreement: 'Ninguno específico en snippet', customsInfo: 'http://english.customs.gov.cn/', logisticalInfo: 'Muy formal, estructurada... Los chinos evitan la confrontación.', detailsLink: 'https://es.distance.to/Beijing,CHN/Beijing,CHN', fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/china_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/china", flagCode: "cn" },
    { id: 'UZB', country: "Uzbekistán", capital: "Taskent", tradeAgreement: "Sin FTA", customsInfo: "https://customs.uz/en/", logisticalInfo: "Formal, jerárquica y protocolar; se respeta mucho la autoridad.", detailsLink: "https://es.distance.to/Beijing,CHN/Tashkent,UZB", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/uzbekistan_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/uzbekistan", flagCode: "uz" },
    { id: 'VNM', country: "Vietnam", capital: "Hanói", tradeAgreement: "ASEAN - China - ASEAN FTA + RCEP", customsInfo: "https://www.customs.gov.vn/index.jsp?pageId=23&groupdId=2&language=en", logisticalInfo: "Formal pero basada en relaciones personales; evitan decir “no” directamente.", detailsLink: "https://es.distance.to/Beijing,CHN/Hanoi,VNM", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/vietnam_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/vietnam", flagCode: "vn" },
    { id: 'IND', country: "India", capital: "Nueva Delhi", tradeAgreement: "En negociación", customsInfo: "https://www.cbic.gov.in/", logisticalInfo: "Jerárquica y relacional. La negociación puede ser larga y detallada.", detailsLink: "https://es.distance.to/Beijing,CHN/New-Delhi,IND", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/india_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/india", flagCode: "in" },
    { id: 'JPN', country: "Japón", capital: "Tokio", tradeAgreement: "CPTPP", customsInfo: "https://www.customs.go.jp/english/", logisticalInfo: "Extremadamente formal, puntual y grupal. El respeto y la etiqueta son vitales.", detailsLink: "https://es.distance.to/Beijing,CHN/Tokyo,JPN", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/japon_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/japon", flagCode: "jp" },
    { id: 'KOR', country: "Corea del Sur", capital: "Seúl", tradeAgreement: "TLC Perú-Corea", customsInfo: "https://www.customs.go.kr/eng/main.do", logisticalInfo: "Rápida, relacional y jerárquica. Se valora la paciencia y el respeto a los mayores.", detailsLink: "https://es.distance.to/Beijing,CHN/Seoul,KOR", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/coreadelsur_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/corea-republica-de", flagCode: "kr" },
  ],
  'africa': [
    { id: 'DZA', country: "Argelia", capital: "Argel", tradeAgreement: "AfCFTA", customsInfo: "https://douane.gov.dz/?lang=fr", logisticalInfo: "Negociación formal y jerárquica, orientada a resultados.", detailsLink: "https://es.distance.to/Johannesburg,ZAF/Algiers,DZA", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/argelia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/argelia", flagCode: "dz" },
    { id: 'TUN', country: "Túnez", capital: "Túnez", tradeAgreement: "AfCFTA", customsInfo: "http://www.douane.gov.tn/", logisticalInfo: "Se valora la cortesía y la construcción de relaciones.", detailsLink: "https://es.distance.to/Johannesburg,ZAF/Tunis,TUN", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/tunez_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/tunez", flagCode: "tn" },
    { id: 'UGA', country: "Uganda", capital: "Kampala", tradeAgreement: "AfCFTA", customsInfo: "https://ura.go.ug/en/", logisticalInfo: "Negociación abierta, se valora la honestidad.", detailsLink: "https://es.distance.to/Johannesburg,ZAF/Kampala,UGA", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/uganda_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/uganda", flagCode: "ug" },
    { id: 'ZMB', country: "Zambia", capital: "Lusaka", tradeAgreement: "SADC; AfCFTA", customsInfo: "https://www.zra.org.zm/", logisticalInfo: "Negociación formal, basada en acuerdos firmes.", detailsLink: "https://es.distance.to/Johannesburg,ZAF/Lusaka,ZMB", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/zambia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/zambia", flagCode: "zm" },
    { id: 'SLE', country: "Sierra Leona", capital: "Freetown", tradeAgreement: "AfCFTA", customsInfo: "https://www.nra.gov.sl/", logisticalInfo: "Negociación relacional, se prioriza la confianza.", detailsLink: "https://es.distance.to/Johannesburg,ZAF/Freetown,SLE", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/sierraleona_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/sierra-leona", flagCode: "sl" },
    { id: 'ZAF', country: "Sudáfrica", capital: "Pretoria", tradeAgreement: "SACU", customsInfo: "https://www.sars.gov.za/", logisticalInfo: "Estilo de negociación directo y profesional, similar al europeo.", detailsLink: "https://es.distance.to/Johannesburg,ZAF/Pretoria,ZAF", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/sudafrica_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/sudafrica", flagCode: "za" },
    { id: 'NGA', country: "Nigeria", capital: "Abuya", tradeAgreement: "AfCFTA", customsInfo: "https://customs.gov.ng/", logisticalInfo: "Enfocada en el precio y las relaciones personales. Puede ser una negociación dura.", detailsLink: "https://es.distance.to/Johannesburg,ZAF/Abuja,NGA", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/nigeria_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/nigeria", flagCode: "ng" },
  ],
  'oceania': [
    { id: 'AUS_mel', country: "Australia", capital: "Melbourne", tradeAgreement: "ALC Perú - Australia", customsInfo: "https://www.abf.gov.au/", logisticalInfo: "Formal, estructurada; muy estricta puntualidad.", detailsLink: "https://es.distance.to/Sydney/Melbourne", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/australia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/australia", flagCode: "au" },
    { id: 'AUS_syd', country: "Australia", capital: "Sídney", tradeAgreement: "ALC Perú - Australia", customsInfo: "https://www.abf.gov.au/", logisticalInfo: "Práctica y enfocada en resultados; valoran la rapidez.", detailsLink: "https://es.distance.to/Sydney/Sydney", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/australia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/australia", flagCode: "au" },
    { id: 'NZL', country: "Nueva Zelanda", capital: "Wellington", tradeAgreement: "CPTPP", customsInfo: "https://www.customs.govt.nz/", logisticalInfo: "Informal, directa y basada en la confianza. Valoran la honestidad y la transparencia.", detailsLink: "https://es.distance.to/Sydney/Wellington", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/nuevazelanda_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/nueva-zelanda", flagCode: "nz" },
    { id: 'FJI', country: "Fiyi", capital: "Suva", tradeAgreement: "No específico", customsInfo: "https://www.frcs.org.fj/", logisticalInfo: "Relajada y comunitaria. Las relaciones personales son importantes.", detailsLink: "https://es.distance.to/Sydney/Suva", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/fiyi_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/fiyi", flagCode: "fj" },
  ],
  'otros': [
    { id: 'GBR', country: "Gran Bretaña", capital: "Londres", tradeAgreement: "TLC Perú-Reino Unido", customsInfo: "https://www.gov.uk/government/organisations/hm-revenue-customs", logisticalInfo: "Profesional y puntual. Se valora la preparación.", detailsLink: "https://es.distance.to/London/London", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/reinounido_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/reino-unido", flagCode: "gb" },
    { id: 'SCT', country: "Escocia", capital: "Edimburgo", tradeAgreement: "Parte de TLC Perú-Reino Unido", customsInfo: "https://www.gov.uk/government/organisations/hm-revenue-customs", logisticalInfo: "Similar a Gran Bretaña, pragmáticos y directos.", detailsLink: "https://es.distance.to/London/Edinburgh", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/reinounido_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/reino-unido", flagCode: "gb-sct" },
    { id: 'MLT', country: "Malta", capital: "La Valeta", tradeAgreement: "Miembro UE", customsInfo: "https://customs.gov.mt/", logisticalInfo: "Relacional y flexible. El inglés es cooficial.", detailsLink: "https://es.distance.to/London/Valletta", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/malta_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/malta", flagCode: "mt" },
    { id: 'IRL', country: "Irlanda", capital: "Dublín", tradeAgreement: "Miembro UE", customsInfo: "https://www.revenue.ie/en/customs-traders-and-agents/index.aspx", logisticalInfo: "Amistosos y relacionales, pero directos en negocios.", detailsLink: "https://es.distance.to/London/Dublin", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/irlanda_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/irlanda", flagCode: "ie" },
    { id: 'CYP', country: "Chipre", capital: "Nicosia", tradeAgreement: "Miembro UE", customsInfo: "https://www.mof.gov.cy/mof/customs/customs.nsf/index_en/index_en?OpenDocument", logisticalInfo: "Orientados a la relación y la hospitalidad.", detailsLink: "https://es.distance.to/London/Nicosia", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/chipre_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/chipre", flagCode: "cy" },
    { id: 'JPN', country: "Japón", capital: "Tokio", tradeAgreement: "CPTPP", customsInfo: "https://www.customs.go.jp/english/", logisticalInfo: "Extremadamente formal, puntual y grupal.", detailsLink: "https://es.distance.to/London/Tokyo", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/japon_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/japon", flagCode: "jp" },
    { id: 'KOR', country: "Corea del Sur", capital: "Seúl", tradeAgreement: "TLC Perú-Corea", customsInfo: "https://www.customs.go.kr/eng/main.do", logisticalInfo: "Rápida, relacional y jerárquica.", detailsLink: "https://es.distance.to/London/Seoul", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/coreadelsur_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/corea-republica-de", flagCode: "kr" },
    { id: 'NZL_N', country: "Nueva Zelanda (Norte)", capital: "Wellington", tradeAgreement: "CPTPP", customsInfo: "https://www.customs.govt.nz/", logisticalInfo: "Informal, directa y basada en la confianza.", detailsLink: "https://es.distance.to/London/Wellington", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/nuevazelanda_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/nueva-zelanda", flagCode: "nz" },
    { id: 'NZL_S', country: "Nueva Zelanda (Sur)", capital: "Christchurch", tradeAgreement: "CPTPP", customsInfo: "https://www.customs.govt.nz/", logisticalInfo: "Similar a la Isla Norte, práctica y directa.", detailsLink: "https://es.distance.to/London/Christchurch", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/nuevazelanda_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/nueva-zelanda", flagCode: "nz" },
    { id: 'BHR', country: "Bahréin", capital: "Manama", tradeAgreement: "No específico", customsInfo: "https://www.bahraincustoms.gov.bh/", logisticalInfo: "Formal y relacional, se valora la paciencia.", detailsLink: "https://es.distance.to/London/Manama", fichaPaisLink: "#", indicadoresLink: "https://datos.bancomundial.org/pais/bahrein", flagCode: "bh" },
    { id: 'IDN', country: "Indonesia", capital: "Yakarta", tradeAgreement: "En negociación", customsInfo: "https://www.beacukai.go.id/", logisticalInfo: "Indirecta y relacional. Evitar la confrontación.", detailsLink: "https://es.distance.to/London/Jakarta", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/indonesia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/indonesia", flagCode: "id" }
  ],
};
