export type SupplierData = {
  continent: string;
  country: string;
  city: string;
  strengths: string;
  weaknesses: string;
  suppliers: string;
  contractType: string;
  quality: string;
  arbitration: string;
};

export const suppliersData: SupplierData[] = [
  {
    continent: 'Africa',
    country: 'Argelia',
    city: 'Argel',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Angola',
    city: 'Luanda',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Benín',
    city: 'Porto-Novo',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Botsuana',
    city: 'Gaborone',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Burkina Faso',
    city: 'Uagadugú',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Burundi',
    city: 'Gitega',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Camerún',
    city: 'Yaundé',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'República Centroafricana',
    city: 'Bangui',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Chad',
    city: 'Yamena',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Congo (República del Congo)',
    city: 'Brazzaville',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'República Democrática del Congo',
    city: 'Kinshasa',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Costa de Marfil',
    city: 'Yamusukro',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Djibouti',
    city: 'Yibuti',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Egipto',
    city: 'El Cairo',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Eritrea',
    city: 'Asmara',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Esuatini (anteriormente Suazilandia)',
    city: 'Mbabane',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Etiopía',
    city: 'Adís Abeba',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Gabón',
    city: 'Libreville',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Gambia',
    city: 'Banjul',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Ghana',
    city: 'Acra',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Guinea',
    city: 'Conakri',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Guinea-Bisáu',
    city: 'Bissau',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Kenia',
    city: 'Nairobi',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Lesoto',
    city: 'Maseru',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Liberia',
    city: 'Monrovia',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Libia',
    city: 'Trípoli',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Malawi',
    city: 'Lilongüe',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Mali',
    city: 'Bamako',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Mauritania',
    city: 'Nuakchot',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Marruecos',
    city: 'Rabat',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Mozambique',
    city: 'Maputo',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Namibia',
    city: 'Windhoek',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Níger',
    city: 'Niamey',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Nigeria',
    city: 'Abuya',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Ruanda',
    city: 'Kigali',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Senegal',
    city: 'Dakar',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Sierra Leona',
    city: 'Freetown',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Somalia',
    city: 'Mogadiscio',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Sudan',
    city: 'Jartum',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Togo',
    city: 'Lomé',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Tanzania',
    city: 'Dodoma',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Tunez',
    city: 'Túnez',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Uganda',
    city: 'Kampala',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Zambia',
    city: 'Lusaka',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Africa',
    country: 'Zimbabue',
    city: 'Harare',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Europa',
    country: '🇦🇱 Albania\nNo UE',
    city: 'Tirana',
    strengths:
      '✓ Costos laborales bajos\n✓ Productos orgánicos en crecimiento\n✓ Proximidad a mercados UE',
    weaknesses:
      '✗ Infraestructura limitada\n✗ Burocracia compleja\n✗ Bajo volumen de producción',
    suppliers:
      'AgroKaraj y Erjoni Agro impulsan la exportación agrícola albanesa, destacando por su calidad, colaboración local y certificaciones internacionales',
    contractType:
      'Los contratos más usados son EXW, FOB, CIF y DDP, adaptándose según el contexto logístico y comercial',
    quality:
      'Certificación orgánica EU\nNormas albanesas limitadas\nEn proceso de adopción ISO 22000',
    arbitration: 'Cámara de Comercio de Albania - Adhesión a Convención de Nueva York',
  },
  {
    continent: 'Europa',
    country: '🇩🇪 Alemania\nUE',
    city: 'Berlin',
    strengths:
      '✓ Tecnología agrícola avanzada\n✓ Estándares de calidad premium\n✓ Excelente logística\n✓ Cumplimiento normativo',
    weaknesses:
      '✗ Costos elevados\n✗ Competencia intensa\n✗ Regulaciones estrictas',
    suppliers:
      'BayWa AG, AGRAVIS y Südzucker Group  son grandes empresas agrícolas y de semillas con presencia global.',
    contractType: 'DDP (Incoterms 2020) - Contratos marco plurianuales',
    quality:
      'ISO 22000\nGlobalGAP\nIFS Food\nBRCGS\nQS (Quality Scheme)',
    arbitration:
      'DIS (German Arbitration Institute) - Reconocimiento internacional bajo UNCITRAL',
  },
  {
    continent: 'Europa',
    country: '🇦🇹 Austria\nUE',
    city: 'Viena',
    strengths:
      '✓ Productos orgánicos premium\n✓ Reputación de calidad\n✓ Ubicación estratégica',
    weaknesses: '✗ Producción limitada\n✗ Precios altos\n✗ Mercado pequeño',
    suppliers:
      'RWA Raiffeisen Ware, Agrana Beteiligungs-ag, Berglandmilch y Bio Austria son actores clave en agricultura, alimentos y productos orgánicos.',
    contractType: 'CIF con contratos de suministro a largo plazo',
    quality: 'ISO 22000\nAMA GütesiegelBio-Garantie\nEU Organic',
    arbitration: 'VIAC (Vienna International Arbitral Centre) - Referencia europea',
  },
  {
    continent: 'Europa',
    country: '🇧🇪 Bélgica\nUE',
    city: 'Bruselas',
    strengths:
      '✓ Hub logístico europeo\n✓ Puerto de Amberes\n✓ Innovación en horticultura',
    weaknesses:
      '✗ Territorio limitado\n✗ Dependencia de importaciones\n✗ Costos operativos altos',
    suppliers:
      "BelOrta, Greenyard, Agristo y Crop's frozen foods son reconocidos exportadores agrícolas, especializados en frutas, verduras y productos procesados.",
    contractType: 'FCA/DAP con contratos spot y forward',
    quality: 'ISO 22000\nBRCIFSFlandria QualityGlobalGAP',
    arbitration:
      'CEPANI (Belgian Centre for Arbitration) - Reconocido internacionalmente',
  },
  {
    continent: 'Europa',
    country: '🇧🇬 Bulgaria\nUE',
    city: 'Sofia',
    strengths:
      '✓ Costos competitivos\n✓ Clima favorable\n✓ Producción de rosas y lavanda',
    weaknesses:
      '✗ Infraestructura en desarrollo\n✗ Corrupción percibida\n✗ Calidad variable',
    suppliers:
      'Agro Trading Bulgaria LTD orientada a cultivos y productos orgánicos, Agraria SA única empresa búlgara dedicada a productos fitosanitarios.',
    contractType: 'FOB/CFR con pagos documentarios',
    quality: 'ISO 22000 (parcial)EU StandardsBDS (Bulgarian Standards)',
    arbitration: 'BCCI Arbitration Court - Convención de Nueva York',
  },
  {
    continent: 'Europa',
    country: '🇨🇿 Chequia\nUE',
    city: 'Praga',
    strengths:
      '✓ Industria cervecera desarrollada\n✓ Buena relación calidad-precio\n✓ Ubicación central',
    weaknesses: '✗ Mercado saturado\n✗ Producción limitada de ciertos cultivos',
    suppliers: 'Agrofert y Czech Hops son importantes en sectores agrícolas y alimentarios del país.',
    contractType: 'CPT/CIP Incoterms con contratos anuales',
    quality: 'ISO 22000Czech MadeGlobalGAPBRC',
    arbitration:
      'Arbitration Court at Czech Chamber of Commerce - UNCITRAL',
  },
  {
    continent: 'Europa',
    country: '🇭🇷 Croacia\nUE',
    city: 'Zagreb',
    strengths: '✓ Aceite de oliva de calidad\n✓ Vinos premium\n✓ Costa adriática',
    weaknesses:
      '✗ Producción fragmentada\n✗ Escala limitada\n✗ Infraestructura mejorable',
    suppliers:
      'Podravka y Fortenova Group son nombres relevantes en agroindustria y alimentos.',
    contractType: 'FOB/FCA con términos de pago L/C',
    quality: 'ISO 22000PDO/PGI (denominaciones protegidas)EU Organic',
    arbitration:
      'Permanent Arbitration Court at Croatian Chamber of Economy - Convención NY',
  },
  {
    continent: 'Europa',
    country: '🇩🇰 Dinamarca\nUE',
    city: 'Copenhague',
    strengths:
      '✓ Líder en producción porcina\n✓ Tecnología agrícola avanzada\n✓ Sostenibilidad',
    weaknesses:
      '✗ Costos muy elevados\n✗ Clima limitante\n✗ Mercado especializado',
    suppliers:
      'Danish Crown, Arla Foods y Danisko A/S son destacados en producción ganadera, alimentos y procesamiento.',
    contractType: 'DDP/DAP con contratos a largo plazo',
    quality: 'ISO 22000Danish Quality MarkØ-mærket (orgánico)Red Tractor',
    arbitration:
      'Danish Institute of Arbitration - Reconocimiento nórdico e internacional',
  },
  {
    continent: 'Europa',
    country: '🇸🇰 Eslovaquia\nUE',
    city: 'Bratislava',
    strengths:
      '✓ Ubicación estratégica\n✓ Costos moderados\n✓ Crecimiento agroindustrial',
    weaknesses: '✗ Mercado pequeño\n✗ Producción limitada\n✗ Competencia regional',
    suppliers:
      'Agrofert Slovakia, Agro Tami y Dairy Slovakia son empresas de agricultura y alimentos del país.',
    contractType: 'CPT/FCA con pagos documentarios',
    quality: 'ISO 22000SNAS (Slovak Standards)GlobalGAP',
    arbitration:
      'Court of Arbitration Slovak Chamber of Commerce - Convención NY',
  },
  {
    continent: 'Europa',
    country: '🇸🇮 Eslovenia\nUE',
    city: 'Liubliana',
    strengths: '✓ Productos premium nicho\n✓ Miel de alta calidad\n✓ Vinos boutique',
    weaknesses: '✗ Producción muy limitada\n✗ Altos costos\n✗ Mercado micro',
    suppliers:
      'Mlekarna Ljubljana lidera en lácteos y SIP STROJNA INDUSTRIJA d.d. dedicada a maquinaría agrícola.',
    contractType: 'FCA/CPT contratos específicos',
    quality: 'ISO 22000EU Quality SchemesSlovenian Quality Mark',
    arbitration: 'Ljubljana Arbitration Centre - Integrado en red europea',
  },
  {
    continent: 'Europa',
    country: '🇪🇸 España\nUE',
    city: 'Madrid',
    strengths:
      '✓ Mayor productor de aceite de oliva\n✓ Frutas y hortalizas\n✓ Clima favorable\n✓ Exportador líder',
    weaknesses:
      '✗ Sequías recurrentes\n✗ Fragmentación productiva\n✗ Competencia interna',
    suppliers:
      'Anecoop, Dcoop y Ebro Foods son exportadores agrícolas y agroindustriales con amplio alcance.',
    contractType: 'FOB/CIF con contratos anuales y spot',
    quality: 'ISO 22000GlobalGAPBRCIFSDOP/IGP',
    arbitration:
      'Corte de Arbitraje de Madrid (CAM) - Convención de Nueva York, UNCITRAL',
  },
  {
    continent: 'Europa',
    country: '🇪🇪 Estonia\nUE',
    city: 'Tallin',
    strengths:
      '✓ Digitalización avanzada\n✓ Productos orgánicos\n✓ E-governance eficiente',
    weaknesses: '✗ Clima riguroso\n✗ Producción limitada\n✗ Mercado pequeño',
    suppliers:
      'E-Piim, Estonian Grain y Valio Estonia son empresas agrícolas y productoras lácteas con exportación.',
    contractType: 'FCA/CPT con pagos electrónicos',
    quality: 'ISO 22000EU OrganicEstonian Quality Label',
    arbitration:
      'Estonian Chamber of Commerce Arbitration - Sistema nórdico-báltico',
  },
  {
    continent: 'Europa',
    country: '🇫🇮 Finlandia\nUE',
    city: 'Helsinki',
    strengths:
      '✓ Productos orgánicos premium\n✓ Berries silvestres\n✓ Sostenibilidad extrema',
    weaknesses: '✗ Costos muy altos\n✗ Temporada corta\n✗ Volúmenes limitados',
    suppliers: 'Valio y Raisio importantes en alimentos y Valtra para tractores agrícolas',
    contractType: 'DDP/DAP contratos a largo plazo',
    quality: 'ISO 22000Hyvää SuomestaLuomu (orgánico finlandés)Nordic Swan',
    arbitration:
      'Finland Chamber of Commerce Arbitration - Reconocimiento nórdico',
  },
  {
    continent: 'Europa',
    country: '🇫🇷 Francia\nUE',
    city: 'París',
    strengths:
      '✓ Mayor productor agrícola UE\n✓ Vinos y quesos de renombre\n✓ AOC/AOP\n✓ Innovación',
    weaknesses:
      '✗ Burocracia compleja\n✗ Costos elevados\n✗ Proteccionismo sectorial',
    suppliers:
      'InVivo (Soufflet), Terrena, Axéréal, Bigard y Lactalis son actores de peso en la agroindustria francesa.',
    contractType: 'FCA/DAP con contratos plurianuales',
    quality: 'ISO 22000Label RougeAOC/AOPAgriculture BiologiqueIFS/BRC',
    arbitration:
      'Cámara de Comercio Internacional Paris - Referencia mundial, UNCITRAL',
  },
  {
    continent: 'Europa',
    country: '🇬🇷 Grecia\nUE',
    city: 'Atenas',
    strengths:
      '✓ Aceite de oliva premium\n✓ Clima mediterráneo\n✓ Productos tradicionales PDO',
    weaknesses:
      '✗ Infraestructura anticuada\n✗ Fragmentación\n✗ Burocracia excesiva',
    suppliers: 'Minerva, Mevgal y Creta Farms son empresas agroalimentarias griegas con exportación.',
    contractType: 'FOB/CFR con L/C o CAD',
    quality: 'ISO 22000PDO/PGI griegoAGROEU Organic',
    arbitration:
      'Athens Chamber of Commerce Arbitration - Convención de Nueva York',
  },
  {
    continent: 'Europa',
    country: '🇭🇺 Hungría\nUE',
    city: 'Budapest',
    strengths:
      '✓ Tierras fértiles\n✓ Paprika y foie gras\n✓ Costos competitivos',
    weaknesses:
      '✗ Infraestructura variable\n✗ Dependencia de subsidios\n✗ Inestabilidad política',
    suppliers:
      'Bonafarm Group, Pick Szeged, Sole-Mizo y Hungerit destacan en la producción alimentaria y agroindustrial.',
    contractType: 'CPT/FCA con contratos anuales',
    quality: 'ISO 22000Hungarian ProductHungaricumGlobalGAP',
    arbitration:
      'Court of Arbitration at Hungarian Chamber of Commerce - Convención NY',
  },
  {
    continent: 'Europa',
    country: '🇮🇹 Italia\nUE',
    city: 'Roma',
    strengths:
      '✓ Productos DOP/IGP reconocidos\n✓ Vinos premium\n✓ Gastronomía mundial\n✓ Diversidad',
    weaknesses:
      '✗ Burocracia lenta\n✗ Producción fragmentada\n✗ Costos elevados',
    suppliers:
      'Ferrero, Barilla, Lavazza, Parmalat y Conserve Italia son líderes mundiales en alimentación y agroindustria.',
    contractType: 'FCA/FOB con contratos específicos por producto',
    quality: 'ISO 22000DOP/IGP/STGBRC/IFSMade in Italy',
    arbitration:
      'Camera Arbitrale di Milano - Alta reputación internacional, UNCITRAL',
  },
  {
    continent: 'Europa',
    country: '🇱🇻 Letonia\nUE',
    city: 'Riga',
    strengths:
      '✓ Productos lácteos\n✓ Orgánicos en crecimiento\n✓ Costos moderados',
    weaknesses:
      '✗ Mercado pequeño\n✗ Clima limitante\n✗ Infraestructura mejorable',
    suppliers:
      'Olainfarm y Riga Varnish and Paint Plant (RVPP) son algunas de las empresas industriales más influyentes en Letonia, destacando en el sector químico.',
    contractType: 'FCA/CPT pagos documentarios',
    quality: 'ISO 22000EU StandardsLatvian Quality Mark',
    arbitration: 'Latvian Chamber of Commerce Arbitration - Sistema báltico',
  },
  {
    continent: 'Europa',
    country: '🇱🇹 Lituania\nUE',
    city: 'Vilna',
    strengths:
      '✓ Cereales y lácteos\n✓ Ubicación logística báltica\n✓ Costos competitivos',
    weaknesses: '✗ Clima frío\n✗ Mercado regional limitado',
    suppliers:
      'Latvijas Piensaimnieks, Dobeles Dzirnavnieks y Rimi Latvia son actores claves en agroindustria y distribución.',
    contractType: 'FCA/CPT con forwards',
    quality: 'ISO 22000Lithuanian QualityGlobalGAPEU Organic',
    arbitration:
      'Vilnius Court of Commercial Arbitration - Red báltica, Convención NY',
  },
  {
    continent: 'Europa',
    country: '🇱🇺 Luxemburgo\nUE',
    city: 'Luxemburgo',
    strengths: '✓ Estabilidad financiera\n✓ Calidad premium\n✓ Hub financiero',
    weaknesses: '✗ Producción mínima\n✗ Costos altísimos\n✗ Mercado micro',
    suppliers: 'Luxlait y Biogros son prominentes en productos orgánicos.',
    contractType: 'DDP contratos especializados',
    quality: 'ISO 22000Lëtzebuerger ProduitEU Organic',
    arbitration:
      'Luxembourg Chamber of Commerce Arbitration - Enfoque financiero internacional',
  },
  {
    continent: 'Europa',
    country: '🇳🇴 Noruega\nNo UE',
    city: 'Oslo',
    strengths:
      '✓ Salmón y productos del mar líderes\n✓ Altísima calidad\n✓ Trazabilidad total',
    weaknesses:
      '✗ Costos extremadamente altos\n✗ No UE (EEA)\n✗ Producción terrestre limitada',
    suppliers:
      'Mowi (Marine Harvest), Lerøy Seafood y Salmar son exportadores clave de productos del mar y lácteos.',
    contractType: 'DDP/CIF contratos a largo plazo',
    quality: 'ISO 22000ASC/MSCNorwegian QualityGLOBALG.A.P.',
    arbitration: 'Norwegian Arbitration - Sistema nórdico, UNCITRAL',
  },
  {
    continent: 'Europa',
    country: '🇵🇱 Polonia\nUE',
    city: 'Varsovia',
    strengths:
      '✓ Mayor productor frutas UE\n✓ Costos competitivos\n✓ Escala productiva\n✓ Lácteos',
    weaknesses:
      '✗ Calidad variable\n✗ Infraestructura en desarrollo\n✗ Fragmentación',
    suppliers:
      'Mlekovita, OSM Piątnica, Grupa Azoty y Cedrob son grandes empresas polacas dedicadas a la producción de lácteos, carne de ave y químicos como melamina y alcohol oxo.',
    contractType: 'CPT/FCA contratos anuales',
    quality: 'ISO 22000Polish QualityGlobalGAPIFS/BRC',
    arbitration:
      'Court of Arbitration at Polish Chamber of Commerce - Convención NY',
  },
  {
    continent: 'Europa',
    country: '🇵🇹 Portugal\nUE',
    city: 'Lisboa',
    strengths:
      '✓ Vinos de Oporto\n✓ Corcho líder mundial\n✓ Aceite de oliva\n✓ Clima favorable',
    weaknesses:
      '✗ Escala limitada\n✗ Sequías\n✗ Infraestructura rural deficiente',
    suppliers:
      'Delta Cafés, Sovena, Lactogal y Group RAR son importantes en café, aceite, lácteos y exportación agrícola.',
    contractType: 'FOB/CIF con L/C',
    quality: 'ISO 22000DOP/IGP portuguésGlobalGAPEU Organic',
    arbitration: 'CAC (Centro de Arbitragem Comercial) - Convención de Nueva York',
  },
  {
    continent: 'Europa',
    country: '🇷🇴 Rumanía\nUE',
    city: 'Bucarest',
    strengths:
      '✓ Tierras agrícolas extensas\n✓ Costos bajos\n✓ Potencial de crecimiento',
    weaknesses: '✗ Infraestructura deficiente\n✗ Corrupción\n✗ Tecnología atrasada',
    suppliers:
      'Agricover, Cargill Romania y Danone Romania son actores en agricultura y alimentos.',
    contractType: 'FOB/CPT con pagos garantizados',
    quality: 'ISO 22000 (adopción creciente)Romanian QualityEU Standards',
    arbitration:
      'Court of International Commercial Arbitration at CCIR - Convención NY',
  },
  {
    continent: 'Europa',
    country: '🇷🇺 Rusia\nNo UE',
    city: 'Moscú',
    strengths:
      '✓ Gran productor de cereales\n✓ Escala masiva\n✓ Precios competitivos',
    weaknesses:
      '✗ Sanciones internacionales\n✗ Riesgo político alto\n✗ Calidad inconsistente\n✗ Logística compleja',
    suppliers: 'Rusagro, Miratorg y Wimm-Bill-Dann son grandes exportadores agroindustriales.',
    contractType: 'FOB Mar Negro - Contratos especiales con garantías',
    quality: 'GOST (estándares rusos)ISO limitadoCertificación propia',
    arbitration:
      'ICAC (International Commercial Arbitration Court at RF CCI) - Reconocimiento limitado por sanciones',
  },
  {
    continent: 'Europa',
    country: '🇸🇪 Suecia\nUE',
    city: 'estocolmo',
    strengths:
      '✓ Sostenibilidad líder\n✓ Productos orgánicos\n✓ Avena y lácteos premium',
    weaknesses:
      '✗ Costos muy altos\n✗ Clima limitante\n✗ Producción limitada',
    suppliers:
      'Lantmännen y Swedish Oat Fiber son relevantes en agroindustria y alimentos.',
    contractType: 'DDP/DAP contratos sostenibles a largo plazo',
    quality: 'ISO 22000KRAV (orgánico sueco)Svenskt SigillNordic Swan',
    arbitration: 'SCC (Stockholm Chamber of Commerce) - Prestigio internacional, UNCITRAL',
  },
  {
    continent: 'Europa',
    country: '🇨🇭 Suiza\nNo UE',
    city: 'Berna',
    strengths:
      '✓ Chocolate premium mundial\n✓ Quesos de calidad\n✓ Estabilidad extrema\n✓ Reputación',
    weaknesses:
      '✗ Costos altísimos\n✗ Producción limitada\n✗ No UE (acuerdos bilaterales)\n✗ Proteccionismo',
    suppliers: 'Nestlé, Lindt & Sprüngli y Emmi Group son gigantes globales de alimentos.',
    contractType: 'DDP contratos especializados premium',
    quality: 'ISO 22000Swiss QualityAOP/AOC suizoBIO Suisse',
    arbitration:
      "Swiss Chambers' Arbitration Institution - Referencia mundial neutral",
  },
  {
    continent: 'Europa',
    country: '🇹🇷 Turquía\nNo UE',
    city: 'Ankara',
    strengths:
      '✓ Frutas secas y avellanas líder\n✓ Ubicación estratégica\n✓ Costos competitivos\n✓ Diversidad',
    weaknesses:
      '✗ Inestabilidad monetaria\n✗ Riesgo político\n✗ Calidad variable',
    suppliers:
      'Erkunt Traktör dedicada a producción de tractores agrícolas y Safa Tarim especializada en productos fitosanitarios y de nutrición vegetal',
    contractType: 'FOB/CIF con pagos L/C confirmadas',
    quality: 'ISO 22000Turkish Standards (TSE)GlobalGAP (exportadores)Halal',
    arbitration:
      'ISTAC (Istanbul Arbitration Centre) - Convención de Nueva York, creciente reconocimiento',
  },
  {
    continent: 'Centro America',
    country: 'Belice',
    city: 'Belmopán',
    strengths:
      'Inglés oficial facilita comunicación; sistema jurídico basado en derecho inglés; régimen fiscal atractivo para IED; Zonas Francas con desgravaciones fiscales.',
    weaknesses: 'Disputa territorial con Guatemala crea incertidumbre; pequeño mercado local.',
    suppliers: 'Belize Agro Enterprise Ltd, Green Care Products Ltd, Quality Feed Mill Ltd',
    contractType:
      'Contratos indefinidos y de duración determinada (empleo); contratos mercantiles tradicionales.',
    quality:
      'Calidad bajo normas internacionales, énfasis en regulaciones regionales; ISO requerido en exportaciones.',
    arbitration:
      'Caso territorial pendiente en CIJ; arbitrajes internacionales para disputas comerciales conforme a tratados multilaterales.',
  },
  {
    continent: 'Centro America',
    country: 'Costa Rica',
    city: 'San José',
    strengths:
      'Economía estable y dinámica; TLCs amplios con varios países; buena infraestructura; respeto por certificaciones internacionales',
    weaknesses:
      'Procedimientos burocráticos lentos; cultura de negociaciones consensuales; retrasos en pagos frecuentes',
    suppliers: 'Agro Pro Centroamérica S.A. líder en fitosanitarios y fertilizantes',
    contractType:
      'Contratos de compraventa, arrendamiento mercantil, distribución y agencia comercial.',
    quality:
      'Uso extendido de ISO 9001:2015 y otras normas ISO (ambiental, seguridad alimentaria).',
    arbitration:
      'Ley unificada de arbitraje nacional e internacional vigente desde 2025; arbitraje bajo normativa Chárter UNCITRAL.',
  },
  {
    continent: 'Centro America',
    country: 'El Salvador',
    city: 'San Salvador',
    strengths:
      'Estabilidad macroeconómica y dolarización; incentivos en zonas francas; ubicación estratégica para distribución regional',
    weaknesses: 'Economia dependiente de remesas, mercado pequeño; inseguridad jurídica.',
    suppliers: 'Proveedores agronegocios apoyados por ley de zonas francas',
    contractType: 'Contrato de compraventa mercantil es el más común',
    quality:
      'ISO 9001 y demás normas ISO aplicadas; organismo OSN certifica bajo estándares internacionales',
    arbitration:
      'Arbitraje práctico con voluntad judicial; asesoría previa recomendada; regulado por Código de Comercio local y acuerdos internacionales.',
  },
  {
    continent: 'Centro America',
    country: 'Guatemala',
    city: 'Ciudad de Guatemala',
    strengths:
      'Unión Aduanera Centroamericana facilita comercio; recursos naturales; mano de obra joven y costo competitivo',
    weaknesses:
      'Inseguridad, burocracia; riesgos legales en indemnizaciones; sistema judicial lento',
    suppliers: 'Grupo Promoagro (productos fitosanitarios, fertilizantes)',
    contractType: 'Contratos de compraventa, arrendamiento, préstamo, servicios profesionales',
    quality: 'Normas ISO reguladas por OSN; ISO 9001, ISO ambiental y otras presentes',
    arbitration:
      'Miembro de OMC, CIADI y tratados multilaterales; uso de arbitraje internacional para resolver controversias comerciales.',
  },
  {
    continent: 'Centro America',
    country: 'Honduras',
    city: 'Tegucigalpa',
    strengths: 'Integración regional; acceso a mercados regionales; sector agrícola importante',
    weaknesses: 'Problemas de seguridad y burocracia; infraestructura limitada',
    suppliers: 'Proveedores locales de fertilizantes y protección de cultivos (no específicos)',
    contractType: 'Contratos mercantiles tradicionales (compraventa, arrendamiento)',
    quality:
      'Adopción gradual de normas ISO para exportaciones; certificaciones exigentes por mercados internacionales',
    arbitration:
      'Arbitraje internacional conforme a tratados y legislación nacional para resolución de conflictos.',
  },
  {
    continent: 'Centro America',
    country: 'Nicaragua',
    city: 'Managua',
    strengths:
      'Estabilidad macroeconómica; reservas internacionales; sectores exportadores orientados a mano de obra intensiva',
    weaknesses:
      'Riesgos políticos y autoritarismo; bajo número de empresas certificadas ISO; financiamiento externo limitado.',
    suppliers: 'Herogra Nicaragua (fertilizantes, bioestimulantes)',
    contractType: 'Contratos de compraventa, préstamo y servicios usuales',
    quality: 'Solo 57 empresas con certificación ISO; proceso de certificación costoso y largo',
    arbitration:
      'Arbitraje internacional flexible, eficiente y confidencial; regulado por leyes nacionales y acuerdos internacionales.',
  },
  {
    continent: 'Norte America',
    country: 'Canadá',
    city: 'Toronto',
    strengths: 'Economía diversificada y estable; normas de calidad exigentes; gran mercado interno',
    weaknesses: 'Altos costos laborales y regulatorios',
    suppliers: 'Grandes proveedores agrícolas nacionales e internacionales',
    contractType: 'Contratos mercantiles formales y detallados',
    quality: 'ISO y estrictas regulaciones sanitarias y fitosanitarias',
    arbitration:
      'Arbitraje internacional respaldado por tratados como el CUSMA; mecanismos robustos para solución de conflictos.',
  },
  {
    continent: 'Centro America',
    country: 'México',
    city: 'Ciudad de México',
    strengths:
      'Gran mercado interno; TLCs amplios; infraestructura avanzada; industria agrícola sólida',
    weaknesses:
      'Burocracia y corrupción en algunos sectores; retos regulatorios en ciertos estados',
    suppliers: 'Proveedores agrarios líderes nacionales y multinacionales',
    contractType: 'Contrato de compraventa, distribución y agencia común',
    quality:
      'Amplia adopción de normas ISO (9001, 14001, etc.); cumplimiento regulatorio estricto',
    arbitration:
      'Uso frecuente de arbitraje según Ley de Comercio Exterior y tratados internacionales vigentes.',
  },
  {
    continent: 'Norte America',
    country: 'Estados Unidos',
    city: 'Texas',
    strengths:
      'Mayor mercado del mundo; infraestructura logística avanzada; gran diversidad agrícola',
    weaknesses: 'Costos altos; compleja regulación estatal y federal',
    suppliers: 'Proveedores líderes en fertilizantes, agroquímicos y maquinarias',
    contractType: 'Contratos de compraventa, distribución, servicios y sublicencias',
    quality: 'Certificaciones ISO, USDA, FDA, normas muy estrictas de calidad y seguridad',
    arbitration:
      'Arbitraje muy común; normas de arbitraje internacional reconocidas; tribunales y cámaras de comercio nacionales reputadas.',
  },
  {
    continent: 'Asia',
    country: 'Afganistán',
    city: 'Kabul',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Arabia Saudita',
    city: 'Riad',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Armenia',
    city: 'Ereván',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Azerbaiyán',
    city: 'Bakú',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Bahréin',
    city: 'Manama',
    strengths:
      'Mercado con poder adquisitivo en GCC; activos importadores/retailers que compran alimentos y productos agrícolas en volumen (Bahréin importa la mayor parte de sus alimentos). Buenas relaciones comerciales dentro del Golfo.',
    weaknesses:
      'Producción local agrícola limitada por clima; alta dependencia de importaciones (riesgo logístico y de precios internacionales). Requisitos regulatorios del Golfo y adaptación a normas regionales (GSO).',
    suppliers:
      'Importadores y distribuidores regionales (varios listados en directorios B2B — p. ej. Go4WorldBusiness, importadores locales como Gulf Food Production WLL y distribuidores de frutas y granos). No hay un “Top 3” monopolizado; el abastecimiento es diversificado.',
    contractType:
      'CIF / CNF y contratos de compraventa internacionales con L/C o TT; compradores bahrainíes suelen acordar condiciones de importación estándar (CIF/FOB y L/C).',
    quality:
      'Bahrain adopta estándares del GCC y normas nacionales (BSMD); hay guías de seguridad alimentaria (Ministerio de Salud) y adopción de estándares internacionales (Codex/GSO). Halal y trazabilidad son requisitos clave en el Golfo.',
    arbitration:
      'Miembro de la Convención de Nueva York desde 1988.\n\nArbitraje regulado por el Decreto-Ley 9/2015, basado en la Ley Modelo UNCITRAL.\n\nSede importante: Bahrain Chamber for Dispute Resolution (BCDR-AAA).\n\nFavorece el arbitraje internacional rápido y en inglés.',
  },
  {
    continent: 'Asia',
    country: 'Bangladés',
    city: 'Daca (Dhaka)',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Birmania (Myanmar)',
    city: 'Naipyidó (Naypyidaw)',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Bután',
    city: 'Thimbu',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Camboya',
    city: 'Nom Pen (Phnom Penh)',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Emiratos Árabes Unidos',
    city: 'Abu Dabi',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'India',
    city: 'Nueva Delhi',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Irán',
    city: 'Teherán',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Irak',
    city: 'Bagdad',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Jordania',
    city: 'Amán',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Kazajistán',
    city: 'Astaná',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Kirguistán',
    city: 'Biskek',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Kuwait',
    city: 'Ciudad de Kuwait',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Laos',
    city: 'Vientián',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Líbano',
    city: 'Beirut',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Malasia',
    city: 'Kuala lumpur',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Mongolia',
    city: 'Ulán Bator (Ulaanbaatar)',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Nepal',
    city: 'Katmandú',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Omán',
    city: 'Mascate',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Pakistán',
    city: 'Islamabad',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Singapur',
    city: 'Ciudad de Sigapur',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Tailandia',
    city: 'Bangkok',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Tayikistán',
    city: 'Dusambé',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Turquía ',
    city: 'Ankara',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Turkmenistán',
    city: 'Asjabad',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Uzbekistán',
    city: 'Taskent',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'Asia',
    country: 'Vietnam',
    city: 'Hanói',
    strengths: '',
    weaknesses: '',
    suppliers: '',
    contractType: '',
    quality: '',
    arbitration: '',
  },
  {
    continent: 'America del Sur',
    country: 'Argentina',
    city: 'Buenos Aires',
    strengths:
      'Argentina cuenta con una fuerte capacidad productiva agrícola y agroindustrial, respaldada por una tecnología avanzada y una amplia red de exportadores. Su ubicación estratégica en el Cono Sur y la calidad de sus productos agroalimentarios le permiten mantener vínculos comerciales con diversos mercados internacionales.',
    weaknesses:
      'La volatilidad económica y cambiaria puede afectar la estabilidad de los contratos. Existen también costos logísticos internos elevados y una burocracia aduanera que puede ralentizar operaciones.',
    suppliers:
      'Cooperativas como la Asociación de Cooperativas Argentinas (ACA) y Agricultores Federados Argentinos (AFA). Grandes exportadores como Bunge, Cargill, Molinos Río de la Plata y Vicentín.',
    contractType:
      'Contratos de compraventa internacional (FOB o CIF), acuerdos forward y contratos de suministro agrícola.',
    quality:
      'Certificaciones: SENASA, HACCP, ISO 22000 y GlobalG.A.P. Argentina cumple con los más altos estándares fitosanitarios internacionales.',
    arbitration:
      'Firmante de la Convención de Nueva York. Arbitraje regulado por el Tribunal de Arbitraje de la Bolsa de Comercio de Buenos Aires, reconocido por su imparcialidad y eficiencia.',
  },
  {
    continent: 'America del Sur',
    country: 'Bolivia',
    city: 'La Paz',
    strengths:
      'Bolivia posee gran biodiversidad agrícola y un creciente interés en productos orgánicos y sostenibles. Es un socio ideal para negociar productos naturales, ecológicos y de origen andino.',
    weaknesses:
      'Su falta de salida al mar encarece los costos logísticos. La infraestructura vial es limitada, y los procesos administrativos suelen ser lentos.',
    suppliers:
      'Cooperativas agrícolas en Santa Cruz y Cochabamba como ANAPO, FEGASACRUZ y asociaciones de productores orgánicos.',
    contractType:
      'Contratos de compraventa y suministro directo, con acuerdos a mediano plazo adaptados a la producción local.',
    quality:
      'Certificaciones: SENASAG, ISO 9001, y normas de producción ecológica. Se valora la trazabilidad del producto.',
    arbitration:
      'Arbitraje regulado por la Ley 708 de Conciliación y Arbitraje. Bolivia es firmante de la Convención de Nueva York. El arbitraje se realiza a través de la Cámara Nacional de Comercio.',
  },
  {
    continent: 'America del Sur',
    country: 'Brasil',
    city: 'Brasilia',
    strengths:
      'Es una de las potencias agrícolas más grandes del mundo. Posee alta productividad, tecnología avanzada, amplios recursos naturales y una infraestructura robusta en transporte marítimo.',
    weaknesses:
      'Altos costos internos de transporte y burocracia en procesos aduaneros. Las regulaciones sanitarias son exigentes y pueden requerir tiempo.',
    suppliers:
      'Empresas líderes: JBS, BRF, Amaggi, Cargill Brasil, y cooperativas agrícolas como Coamo y Copacol.',
    contractType:
      'Contratos de compraventa internacional y contratos forward en mercados de granos. También se usan acuerdos de cooperación productiva.',
    quality:
      'Certificaciones: MAPA, ANVISA, ISO 22000, HACCP, y GlobalG.A.P.',
    arbitration:
      'Arbitraje administrado por la Cámara de Comercio Brasil-Canadá (CCBC). Firmante de la Convención de Nueva York. Amplio uso del arbitraje comercial internacional.',
  },
  {
    continent: 'America del Sur',
    country: 'Chile',
    city: 'Santiago',
    strengths:
      'Chile es reconocido por su estabilidad económica, políticas de libre comercio y apertura a la inversión extranjera. Es un país confiable, con altos estándares de calidad y certificaciones internacionales.',
    weaknesses:
      'Altos costos de vida y transporte interno. El mercado es competitivo y tiene requisitos de calidad elevados.',
    suppliers:
      'Principales proveedores: Frutas de Chile (ASOEX), Agrosuper, Hortifrut, Viña Concha y Toro.',
    contractType:
      'Contratos de compraventa internacional bajo la CISG y acuerdos de largo plazo con distribuidores.',
    quality:
      'Certificaciones: SAG, HACCP, BRC, ISO 9001, GlobalG.A.P. y buenas prácticas agrícolas obligatorias.',
    arbitration:
      'Arbitraje administrado por el CAM Santiago (Centro de Arbitraje y Mediación). Chile es firmante de la Convención de Nueva York y cuenta con un sistema judicial confiable.',
  },
  {
    continent: 'America del Sur',
    country: 'Colombia',
    city: 'Bogota',
    strengths:
      'Colombia combina una posición geográfica estratégica con una oferta agrícola diversa (café, flores, frutas tropicales). Posee múltiples acuerdos comerciales internacionales y una economía estable en expansión.',
    weaknesses:
      'Inseguridad jurídica en ciertas zonas rurales y costos logísticos elevados, especialmente en transporte marítimo y portuario.',
    suppliers:
      'Federación Nacional de Cafeteros, Fedepalma, Procaña, C.I. Tequendama, Flores de Colombia.',
    contractType:
      'Contratos de compraventa internacional y contratos marco con distribuidores nacionales.',
    quality:
      'Certificaciones: INVIMA, ICA, ISO 22000, Rainforest Alliance y GlobalG.A.P.',
    arbitration:
      'Arbitraje administrado por el Centro de Arbitraje de la Cámara de Comercio de Bogotá. Colombia es firmante de la Convención de Nueva York y promueve mecanismos alternativos de resolución de conflictos.',
  },
  {
    continent: 'America del Sur',
    country: 'Ecuador',
    city: 'Quito',
    strengths:
      'Destacado por su producción orgánica y de alta calidad, especialmente en cacao, banano y flores. Mantiene políticas de promoción de exportaciones y una estructura logística eficiente hacia puertos del Pacífico.',
    weaknesses:
      'Dependencia del transporte marítimo y variabilidad en regulaciones aduaneras.',
    suppliers: 'Proveedores: Anecacao, Agroban, Expoflores, Pronaca y Pacari.',
    contractType:
      'Contratos de compraventa FOB o CIF, con cláusulas de calidad y cumplimiento fitosanitario.',
    quality: 'Certificaciones: AGROCALIDAD, ISO 22000, HACCP, GlobalG.A.P.',
    arbitration:
      'Arbitraje regulado por la Ley de Arbitraje y Mediación; administrado por la Cámara de Comercio de Quito. Ecuador es firmante de la Convención de Nueva York.',
  },
  {
    continent: 'America del Sur',
    country: 'Paraguay',
    city: 'Asunción',
    strengths:
      'Paraguay ofrece bajos costos de producción, incentivos fiscales para inversiones agrícolas y un entorno comercial estable. Se especializa en granos, soja y carne bovina.',
    weaknesses:
      'No posee salida al mar, lo que encarece el transporte internacional. Su infraestructura vial es limitada.',
    suppliers: 'Cooperativas: Colonias Unidas, Coopasam, Agrofértil, Frigorífico Neuland.',
    contractType: 'Contratos de suministro agrícola y exportación a mediano y largo plazo.',
    quality:
      'Certificaciones: SENAVE, ISO 9001, BPA (Buenas Prácticas Agrícolas), trazabilidad animal.',
    arbitration:
      'Arbitraje gestionado por el Centro de Arbitraje y Mediación del Paraguay (CAMP). Paraguay es firmante de la Convención de Nueva York.',
  },
  {
    continent: 'America del Sur',
    country: 'Uruguay',
    city: 'Montevideo',
    strengths:
      'País con estabilidad institucional, transparencia en sus políticas y cumplimiento riguroso de contratos. Tiene excelente reputación en carne y lácteos.',
    weaknesses: 'Mercado pequeño y altos costos laborales. Limitada capacidad de producción a gran escala.',
    suppliers: 'Cooperativas: Conaprole, Central Lanera Uruguaya, Frigocerro, Marfrig Uruguay.',
    contractType:
      'Contratos de compraventa internacional y de suministro bajo normas de calidad certificadas.',
    quality: 'Certificaciones: INAC, ISO 22000, GlobalG.A.P., HACCP.',
    arbitration:
      'Arbitraje administrado por el Centro de Conciliación y Arbitraje de la Cámara de Comercio del Uruguay. Firmante de la Convención de Nueva York.',
  },
  {
    continent: 'America del Sur',
    country: 'Venezuela',
    city: 'Caracas',
    strengths:
      'Posee abundantes recursos naturales y potencial agrícola. Hay interés en reactivar su producción agroindustrial y exportaciones.',
    weaknesses:
      'Inestabilidad económica, controles de precios y sistema cambiario rígido. Dificultad en pagos internacionales.',
    suppliers: 'Asociaciones agrícolas locales dedicadas a cacao, café y frutas tropicales.',
    contractType:
      'Contratos privados de suministro, permutas y acuerdos informales adaptados a la realidad económica.',
    quality:
      'Certificaciones nacionales (SENCAMER) y bajo cumplimiento de normas ISO por la situación económica.',
    arbitration:
      'Arbitraje bajo la Cámara de Comercio de Caracas. Venezuela es firmante de la Convención de Nueva York, aunque el entorno institucional puede ser complejo.',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Londres',
    strengths: 'Tradición agrícola, infraestructura logística, tecnología avanzada, altos estándares de calidad y sostenibilidad.',
    weaknesses: 'Volatilidad post-Brexit, costos operativos, dependencia de mano de obra estacional, nuevas barreras regulatorias.',
    suppliers: 'Wealmoor Ltd, Organic Farm Foods, Hider Food Imports, Daylesford Organics, Clean Food Group, más de 100 empresas agrícolas',
    contractType: 'Contratos internacionales FOB/CIF, forward, suministro, farming contracts',
    quality: 'GlobalG.A.P., BRC, ISO 9001, ISO 22000, IFS, FSSC 22000, regulaciones nacionales y europeas',
    arbitration: 'Ley de Arbitraje AA 2025, Londres como sede frecuente, reconocimiento internacional',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Manchester',
    strengths: 'Zona mixta de cultivos y ganadería, buena conectividad por tren',
    weaknesses: 'Suelos menos fértiles fuera del cinturón verde, competencia por uso de suelo',
    suppliers: 'Proveedores regionales de carne y lácteos, pequeñas cooperativas.',
    contractType: 'Suministro local y acuerdos forward.',
    quality: 'Cumple regulaciones agrícolas nacionales.',
    arbitration: 'Arbitraje en Manchester/Londres.',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Birmingham',
    strengths: 'Región industrial con presencia agroalimentaria, acceso logístico.',
    weaknesses: 'Urbanización intensa, menor relevancia agrícola directa.',
    suppliers: 'Distribuidores de insumos y procesadores.',
    contractType: 'Contratos de distribución y venta regional.',
    quality: 'Normas generalizadas ISO, BRC.',
    arbitration: 'Tribunales regionales/Londres.',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Liverpool',
    strengths: 'Acceso a puerto, comercio internacional, productos frescos importados.',
    weaknesses: 'Menor superficie agrícola, dependencia de importación.',
    suppliers: 'Importadores y mayoristas de productos agrícolas.',
    contractType: 'Contratos FOB/CIF portuarios.',
    quality: 'BRC, normas fitoportuarias.',
    arbitration: 'Tribunales de Liverpool/Londres.',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Leeds',
    strengths: 'Producción mixta agrícola, fuerte actividad de mercados.',
    weaknesses: 'Competencia en agroindustria, clima variable.',
    suppliers: 'Cooperativas regionales de cereales y vegetales.',
    contractType: 'Acuerdos de suministro agrícola.',
    quality: 'GlobalG.A.P., ISO 22000.',
    arbitration: 'Tribunales de Leeds/Londres.\n',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Bristol',
    strengths: 'Zona mixta agrícola y ganadera, concentración en agricultura sostenible.',
    weaknesses: 'Presión urbana y ambiental, costos altos.',
    suppliers: 'Productores orgánicos, mercados de alimentos frescos.',
    contractType: 'Acuerdos de productos orgánicos y sostenibles.',
    quality: 'Cumple exigencias ecológicas locales.',
    arbitration: 'Arbitraje local/Londres.',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Oxford',
    strengths: 'Producción de vegetales y cereales, cerca de zonas de cultivo de alto rendimiento.',
    weaknesses: 'Presión del desarrollo urbano y educativo.',
    suppliers: 'Granjas regionales y proveedores ecológicos.',
    contractType: 'Farming contracts y distribución local.',
    quality: 'Normas ISO, GlobalG.A.P.',
    arbitration: 'Arbitraje Oxford/Londres.\n',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Cambridge',
    strengths: 'Zona agrícola de alta productividad, innovación tecnológica agrícola.',
    weaknesses: 'Riesgo climático (inundaciones), regulación ambiental estricta.',
    suppliers: 'Empresas tecnológicas agrícolas, productores innovadores.',
    contractType: 'Farming contracts, acuerdos forward.',
    quality: 'ISO 22000, GlobalG.A.P.',
    arbitration: 'Arbitraje en Cambridge/Londres.\n',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Sheffield',
    strengths: 'Principalmente ganadería y pastoreo, granjas familiares.',
    weaknesses: 'Topografía montañosa, menor producción de cultivos.',
    suppliers: 'Proveedores de carne y lácteos, cooperativas familiares.',
    contractType: 'Suministro local, acuerdos ganaderos.',
    quality: 'Normas nacionales porcinas y lácteas.',
    arbitration: 'Tribunales Sheffield/Londres.\n',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Newcastle upon Tyne',
    strengths: 'Región ganadera y de cereales, mercado portuario.',
    weaknesses: 'Clima frío limita producción de ciertas frutas y vegetales.',
    suppliers: 'Proveedores de trigo, patata y carne.',
    contractType: 'Contratos portuarios y de grano.',
    quality: 'Cumple normativa nacional.',
    arbitration: 'Arbitraje Newcastle/Londres.\n',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Nottingham',
    strengths: 'Mezcla de cultivo de cereales y horticultura.',
    weaknesses: 'Suelo no siempre óptimo, competencia regional.',
    suppliers: 'Horticultores, cooperativas regionales.',
    contractType: 'Farming contracts y acuerdos de suministro.',
    quality: 'GlobalG.A.P., ISO 9001.',
    arbitration: 'Tribunales Nottingham/Londres.\n',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Southampton',
    strengths: 'Ciudad portuaria, acceso a productos importados, agricultura mixta.',
    weaknesses: 'Espacio agrícola limitado, presión turística.',
    suppliers: 'Productores hortícolas y importadores portuarios.',
    contractType: 'Contratos CIF/FOB y de distribución.',
    quality: 'Normas portuarias y fitosanitarias.',
    arbitration: 'Tribunales Southampton/Londres.\n',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Brighton',
    strengths: 'Agricultura urbana, mercados orgánicos, clima suave.',
    weaknesses: 'Suelo limitado y competencia inmobiliaria.',
    suppliers: 'Pequeños productores ecológicos y mercados locales.',
    contractType: 'Acuerdos de productos frescos y orgánicos.',
    quality: 'BRC, GlobalG.A.P., ecológico local.',
    arbitration: 'Tribunales Brighton/Londres.',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Bath',
    strengths: 'Agricultura tradicional y ecológica, mercado turístico.',
    weaknesses: 'Terreno ondulado, menor escala industrial.',
    suppliers: 'Productores regionales ecológicos, mercados.',
    contractType: 'Contratos de pequeños volúmenes.',
    quality: 'Cumple exigencias turísticas y ecológicas.',
    arbitration: 'Arbitraje Bath/Londres.\n',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Cardiff',
    strengths: 'Región agrícola variada, fuerte producción ganadera en Gales.',
    weaknesses: 'Exposición al clima húmedo, dependencia ganadera.',
    suppliers: 'Cooperativas galesas, productores familiares.',
    contractType: 'Contratos ganaderos y de cereales.',
    quality: 'Normas nacionales y Galesas.',
    arbitration: 'Tribunales Cardiff/Londres.',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Milton Keynes',
    strengths: 'Área periurbana con explotaciones agrícolas medianas.',
    weaknesses: 'Crecimiento urbano, presión sobre la tierra.',
    suppliers: 'Granjas periurbanas, mercados frescos.',
    contractType: 'Contratos agrícolas y acuerdos locales.',
    quality: 'Cumplir regulaciones nacionales y urbanas.',
    arbitration: 'Arbitraje Milton Keynes/Londres.',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'York',
    strengths: 'Región agrícola histórica, mezcla de cereales, leche y vegetales.',
    weaknesses: 'Competencia regional, fluctuaciones climáticas.',
    suppliers: 'Productores de lácteos, cereales, verduras.',
    contractType: 'Contratos agrícolas y suministro local.',
    quality: 'Normas nacionales británicas.',
    arbitration: 'Tribunales de York/Londres.',
  },
  {
    continent: 'Europa',
    country: 'Gran Bretaña',
    city: 'Sunderland',
    strengths: 'Agricultura mixta, presencia de pesca y ganadería.',
    weaknesses: 'Terreno variado, presión industrial costera.',
    suppliers: 'Productores mixtos y cooperativas pesqueras.',
    contractType: 'Contratos mixtos agrícolas-pesqueros.',
    quality: 'ISO 9001, regulaciones portuarias.',
    arbitration: 'Arbitraje Sunderland/Londres.\n',
  },
  {
    continent: 'Europa',
    country: 'Escocia',
    city: 'Edimburgo',
    strengths:
      'Centro de servicios, apoyo gubernamental, acceso a innovación agrícola ya mercados internacionales; liderazgo en sostenibilidad y transferencia de tecnología',
    weaknesses:
      'Altos costos urbanos, menor actividad productiva directa, dependencia de zonas rurales.',
    suppliers: 'Empresas de agrotecnología, distribuidores y exportadores.',
    contractType: 'Contratos colaborativos y de exportación.',
    quality:
      'Cumplimiento con normas ISO europeas y británicas, GlobalG.AP y políticas de sostenibilidad local.',
    arbitration: 'Tribunales de Edimburgo, ley británica y convenios internacionales.\n',
  },
  {
    continent: 'Europa',
    country: 'Escocia',
    city: 'Glasgow',
    strengths: 'Conexión portuaria, procesamiento de alimentos, acceso a mano de obra y comercio exterior.',
    weaknesses: 'Urbanización intensa, presión ambiental y costos altos.',
    suppliers: 'Procesadores de alimentos, distribuidores portuarios, cooperativas regionales.',
    contractType: 'Contratos portuarios y de cadena de suministro.',
    quality: 'Cumplen exigencias alimentarias británicas, BRC y estándares de exportación.',
    arbitration: 'Tribunales de Glasgow, legislación escocesa.',
  },
  {
    continent: 'Europa',
    country: 'Escocia',
    city: 'Aberdeen',
    strengths:
      'Zona importante de ganadería y cereales, cerca del Mar del Norte (logística exportadora eficiente)',
    weaknesses: 'Clima muy frío limita algunos cultivos, alta dependencia de la ganadería.',
    suppliers: 'Cooperativas ganaderas, exportadoras de cebada y trigo.',
    contractType: 'Contratos agrícolas, acuerdos de exportación.',
    quality: 'Normas fitosanitarias escocesas y ecológicas.',
    arbitration: 'Arbitraje Aberdeen y convenios internacionales.\n',
  },
  {
    continent: 'Europa',
    country: 'Escocia',
    city: 'Dundee',
    strengths:
      'Historial en agricultura de frutas y hortalizas, fuerte industria innovadora y acceso portuario.',
    weaknesses: 'Limitación de superficie agrícola, competencia urbana/turística.',
    suppliers: 'Productores de frutas y verduras, cooperativas hortícolas.',
    contractType: 'Contratos agrícolas, acuerdos con supermercados y exportación.',
    quality: 'Certificaciones GlobalG.AP, ISO 22000.',
    arbitration: 'Tribunales Dundee/Escocia.\n',
  },
  {
    continent: 'Europa',
    country: 'Escocia',
    city: 'Inverness',
    strengths:
      'Territorio destacado en ganadería extensiva y agricultura ecológica, paisajes rurales y turismo agrícola.',
    weaknesses: 'Condiciones climáticas adversas, dispersión geográfica, dificultades logísticas.',
    suppliers: 'Productores ecológicos, carne y lácteos (Highlands).',
    contractType: 'Contratos para carne ecológica, acuerdos regionales.',
    quality: 'Certificaciones ecológicas británicas/regionales.',
    arbitration: 'Tribunales de Inverness, arbitraje escocés.',
  },
  {
    continent: 'Europa',
    country: 'Escocia',
    city: 'Stirling',
    strengths:
      'Agricultura cerealista, tradición en cultivos de trigo y cebada, apoyo universitario y técnico.',
    weaknesses: 'Clima húmedo, presión de modernización productiva.',
    suppliers: 'Proveedores de grano y cooperativas regionales.',
    contractType: 'Contratos y acuerdos agrarios en el futuro.',
    quality: 'ISO 9001, GlobalG.AP, normas cerealistas UK.',
    arbitration: 'Tribunales Stirling/Escocia.',
  },
  {
    continent: 'Europa',
    country: 'Escocia',
    city: 'Perth',
    strengths:
      'Región mixta: ganadería, animales menores, producción de forrajes, buen acceso logístico.',
    weaknesses: 'Competencia en precios, fluctuaciones de mercado agropecuario.',
    suppliers: 'Cooperativas rurales, productores mixtos.',
    contractType: 'Contratos agrícolas y acuerdos de suministro regionales.',
    quality: 'Cumple normativa nacional, estándares ganaderos.',
    arbitration: 'Tribunales de Perth, convenios internacionales.\n',
  },
  {
    continent: 'Europa',
    country: 'Escocia',
    city: 'Elgin',
    strengths:
      'Agricultura y ganadería diversificadas, pequeñas granjas familiares, énfasis en sostenibilidad',
    weaknesses: 'Menor escala productiva, desafíos para exportación directa, aislamiento logístico.',
    suppliers: 'Granjas familiares, cooperativas agrícolas.',
    contractType: 'Contratos de volumen bajo, asociaciones rurales.',
    quality: 'Certificación escocesa y británica sostenible.',
    arbitration: 'Tribunales de Elgin/regionales.',
  },
  {
    continent: 'Europa',
    country: 'MALTA',
    city: 'Valeta',
    strengths:
      'Centro administrativo y portuario clave con acceso directo a mercados internacionales. Apoyo gubernamental para la modernización agrícola.',
    weaknesses: 'Limitación en tierras agrícolas, alta dependencia de importaciones, costos elevados.',
    suppliers: 'Pequeñas granjas locales, importadores de productos frescos y procesados.',
    contractType: 'Contratos de importación y distribución local.',
    quality:
      'Cumplimiento con normativas EU y Malta, certificaciones GlobalG.AP y agricultura ecológica.',
    arbitration: 'Cámara de comercio de Malta, mecanismos de arbitraje europeos.',
  },
  {
    continent: 'Europa',
    country: 'MALTA',
    city: 'Vittoriosa',
    strengths: 'Infraestructura portuaria para exportación, proximidad a centros de procesamiento.',
    weaknesses: 'Superficie agrícola fragmentada, alta presión urbanística.',
    suppliers: 'Exportadores agrícolas, cooperativas para frutas y verduras.',
    contractType: 'Acuerdos de exportación y contratos adelante.',
    quality: 'Normas europeas exigentes, certificaciones fitosanitarias.',
    arbitration: 'Arbitraje local y europeo reconocidos.',
  },
  {
    continent: 'Europa',
    country: 'MALTA',
    city: 'Cospicua',
    strengths:
      'Ubicación estratégica para comercio marítimo, experiencia en producción agrícola local artesanal.',
    weaknesses: 'Fragmentación del suelo, sistemas agrícolas pequeños.',
    suppliers: 'Granjas familiares, productores locales de hortalizas.',
    contractType: 'Contratos de suministro local y asociaciones rurales.',
    quality: 'Normas de calidad y sostenibilidad aplicadas regionalmente.',
    arbitration: 'Mecanismos de arbitraje integrados en la legislación local.',
  },
  {
    continent: 'Europa',
    country: 'MALTA',
    city: 'Senglea',
    strengths: 'Cercanía a puertos y centros logísticos, mercado de productos frescos y procesados.',
    weaknesses: 'Limitaciones de espacio y recursos naturales, dependencia de importaciones.',
    suppliers: 'Cooperativas pequeñas, proveedoras de cultivos tradicionales.',
    contractType: 'Contratos de distribución, acuerdos locales sostenibles.',
    quality: 'Cumplimiento de regulación agraria maltesa y europea.',
    arbitration: 'Uso de tribunales comerciales y arbitraje internacional.',
  },
  {
    continent: 'Europa',
    country: 'IRLANDA',
    city: 'Dublin',
    strengths:
      'Centro económico clave, acceso a mercados internacionales, infraestructuras avanzadas, apoyo tecnológico agrícola.',
    weaknesses:
      'Alta competencia, costos elevados, espacio limitado para producción agrícola directa.',
    suppliers: 'Grandes importadores, agroindustria avanzada, innovación tecnológica agrícola.',
    contractType: 'Contratos internacionales FOB/CIF y distribución local.',
    quality: 'Normas ISO, GlobalG.A.P., cumplimiento regulatorio europeo e irlandés.',
    arbitration: 'Tribunales de Dublin, arbitraje internacional conforme a convenios.\n',
  },
  {
    continent: 'Europa',
    country: 'IRLANDA',
    city: 'Cork',
    strengths:
      'Importante centro portuario y agrícola, diversidad productiva, acceso a mercados europeos.',
    weaknesses: 'Competencia regional, presiones urbanísticas moderadas.',
    suppliers: 'Cooperativas agrícolal locales, exportadores de productos frescos y procesados.',
    contractType: 'Farming contracts y acuerdos de suministro.',
    quality: 'Certificaciones GlobalG.A.P., normas europeas.',
    arbitration: 'Arbitraje local y europeo.\n',
  },
  {
    continent: 'Europa',
    country: 'IRLANDA',
    city: 'Galway',
    strengths:
      'Región con fuerte producción hortícola y lechera, tradición en agricultura sostenible.',
    weaknesses: 'Limitaciones climáticas, infraestructura rural por mejorar.',
    suppliers: 'Productores intensivos hortícolas y ganaderos.',
    contractType: 'Contratos de suministro local y distribución.',
    quality: 'Cumplimiento de normas agroalimentarias europeas.',
    arbitration: 'Tribunales regionales con apoyo a arbitraje internacional.\n',
  },
  {
    continent: 'Europa',
    country: 'IRLANDA',
    city: 'Límerick',
    strengths: 'Centro agrícola mixto, fuerte en ganadería y cereales, buenas conexiones logísticas.',
    weaknesses: 'Costos en expansión agrícola, presión para modernización.',
    suppliers: 'Cooperativas ganaderas, proveedores de cereales.',
    contractType: 'Contratos forward y de distribución.',
    quality: 'Normas ISO y certificaciones específicas de ganadería.',
    arbitration: 'Arbitraje regional y cooperación jurídica europea.\n',
  },
  {
    continent: 'Europa',
    country: 'IRLANDA',
    city: 'Dundalk',
    strengths:
      'Importante en agricultura de mercado y productos de temporada, acceso a mercados británicos y europeos.',
    weaknesses: 'Limitaciones en tamaño de explotaciones y competencia internacional.',
    suppliers: 'Proveedores hortícolas y agrícolas locales.',
    contractType: 'Acuerdos de agricultura contractuada.',
    quality: 'Normas y regulaciones nacionales y europeas.',
    arbitration: 'Tribunales de Dundalk y resolución de conflictos internacionales.\n',
  },
  {
    continent: 'Europa',
    country: 'IRLANDA',
    city: 'Waterford',
    strengths:
      'Zona con producción variada, portuaria estratégica, buen acceso a exportación.',
    weaknesses: 'Dependencia de productos importados, presión demográfica urbana.',
    suppliers: 'Productores agrícolas y cooperativas litorales.',
    contractType: 'Contratos de exportación y distribución local.',
    quality: 'Normas fitosanitarias y de calidad exigidas por la UE.',
    arbitration: 'Arbitraje conforme a legislación europea y local.\n',
  },
  {
    continent: 'Europa',
    country: 'IRLANDA',
    city: 'Drogheda',
    strengths:
      'Agricultura diversificada, importante centro comercial y logístico, fuerte en producción hortícola.',
    weaknesses: 'Competencia regional, infraestructura rural desconectada.',
    suppliers: 'Productores hortícolas y cooperativas.',
    contractType: 'Farming contracts y contratos forward.',
    quality: 'Certificaciones GlobalG.A.P., cumplimiento EU.',
    arbitration: 'Arbitraje local con apoyo jurídico internacional.\n',
  },
  {
    continent: 'Europa',
    country: 'IRLANDA',
    city: 'Navan',
    strengths:
      'Tradición agrícola en cereales y ganadería, fuerte apoyo comunitario, acceso a mercados irlandeses.',
    weaknesses: 'Limitaciones por tamaño de explotaciones, variabilidad climática.',
    suppliers: 'Cooperativas agrícolas y ganaderas rurales.',
    contractType: 'Contratos de suministro y asociación.',
    quality: 'Normativas nacionales y certificaciones ISO.',
    arbitration: 'Tribunales regionales y arbitraje reconocidos.',
  },
  {
    continent: 'Europa',
    country: 'IRLANDA',
    city: 'Bray',
    strengths:
      'Agricultura periurbana con enfoque en mercados locales y sostenibilidad, acceso a la capital.',
    weaknesses: 'Restricciones urbanísticas, espacio limitado para producción extensiva.',
    suppliers: 'Pequeños productores ecológicos y mercados locales.',
    contractType: 'Acuerdos de agricultura urbana y suministro.',
    quality: 'Cumplimiento con normativas urbanas y certificaciones ecológicas.',
    arbitration: 'Arbitraje conforme a legislación local y europea.\n',
  },
  {
    continent: 'Europa',
    country: 'Chipre',
    city: 'Nicosia',
    strengths:
      'Centro administrativo y económico, apoyo gubernamental para la modernización agrícola, acceso a mercados UE.',
    weaknesses:
      'Sufre limitación de tierras para la agricultura extensiva, alta dependencia de importación.',
    suppliers: 'Cooperativas agrícolas y proveedores locales.',
    contractType: 'Contratos de suministro y exportación.',
    quality: 'Cumplimiento con normativas UE y certificaciones GlobalG.A.P. y ecológicas.',
    arbitration: 'Tribunales en Nicosia con apoyo a arbitraje europeo.\n',
  },
  {
    continent: 'Europa',
    country: 'Chipre',
    city: 'Limassol',
    strengths:
      'Importante puerto para exportación, fuerte infraestructura logística, impulso al turismo rural y agroindustrial.',
    weaknesses: 'Urbanización creciente, limitaciones en extensión agrícola.',
    suppliers: 'Exportadores agrícolas, cooperativas frutícolas.',
    contractType: 'Contratos de exportación y farming contracts.',
    quality: 'Normas fitosanitarias europeas y locales.',
    arbitration: 'Arbitraje internacional según convenios UE.\n',
  },
  {
    continent: 'Europa',
    country: 'Chipre',
    city: 'Lárnaca',
    strengths:
      'Zona agrícola con presencia de cultivos hortícolas y producción intensiva, buen acceso a puertos.',
    weaknesses: 'Presión ambiental, fragmentación del suelo, variabilidad climática.',
    suppliers: 'Productores hortícolas y agroindustriales.',
    contractType: 'Contratos forward y distribución local.',
    quality: 'Normativas UE robustas y certificados ecológicos.',
    arbitration: 'Tribunales y arbitraje local y europeo.\n',
  },
  {
    continent: 'Europa',
    country: 'Chipre',
    city: 'Famagusta',
    strengths:
      'Producción agrícola tradicional, desarrollo de mercados locales, crecimiento en agricultura sostenible.',
    weaknesses: 'Afectada por cuestiones políticas y de seguridad, menor inversión extranjera.',
    suppliers: 'Productores locales y asociaciones agrícolas.',
    contractType: 'Contratos de pequeña escala y asociaciones cooperativas.',
    quality: 'Normas nacionales e internacionales de calidad.',
    arbitration: 'Arbitraje regulado por legislación chipriota y europea.\n',
  },
  {
    continent: 'Europa',
    country: 'Chipre',
    city: 'Pafos',
    strengths: 'Agricultura de calidad, potencial en cultivos orgánicos y turismo agrícola.',
    weaknesses: 'Limitación de recursos hídricos y accesibilidad.',
    suppliers: 'Agronegocios enfocados en productos orgánicos y frescos.',
    contractType: 'Contratos de cultivo orgánico y exportación.',
    quality: 'Certificaciones ecológicas y de sostenibilidad europeas.',
    arbitration: 'Tribunales regionales con base en normativas UE.\n',
  },
  {
    continent: 'Europa',
    country: 'Chipre',
    city: 'Kyrenia',
    strengths:
      'Valor estratégico por proximidad al mar, agricultura mediterránea especializada, potencial turístico.',
    weaknesses: 'Situación política dividida, limitaciones legales.',
    suppliers: 'Cooperativas agrícolas regionales.',
    contractType: 'Acuerdos locales y contratos de exportación limitada.',
    quality: 'Cumplimiento con exigencias UE, certificados de calidad.',
    arbitration: 'Arbitraje internacional reconocido y local.\n',
  },
  {
    continent: 'Asia',
    country: 'Japon',
    city: 'JPN',
    strengths:
      'Mercado con alta capacidad de pago y cadenas logísticas muy desarrolladas (buen poder de compra para productos agrícolas de calidad).\n \nNormativa clara para estándares alimentarios (JAS) y controles sanitarios; consumidores exigen trazabilidad y calidad.',
    weaknesses:
      'Altas exigencias regulatorias y de etiquetado; preferencia por productos con certificaciones (JAS, ISO 22000/FSSC). Requisitos de idioma (etiquetado en japonés).\n \nMercado altamente competitivo con grandes trading houses (Mitsubishi, Marubeni, Itochu) que dominan canales.',
    suppliers:
      'Grandes casas comerciales: Marubeni, Mitsubishi, Itochu (actúan como compradores/distribuidores en alimentos). \n\nPlataformas y distribuidores locales (ej. listados B2B y directorios industriales).',
    contractType:
      'Contract farming / acuerdos de producción y contratos de compraventa con especificaciones técnicas (cantidad, calibre, calidad, fecha de entrega). También uso creciente de contratos integrados por trading houses (contratos de suministro + logística).',
    quality:
      'Normas nacionales JAS (Japanese Agricultural Standards) para diversos productos; Food Sanitation Act para seguridad alimentaria. Certificaciones internacionales (ISO 22000, FSSC 22000, HACCP) son altamente valoradas.',
    arbitration:
      'Miembro de la Convención de Nueva York (1958), reconoce laudos extranjeros.\n\nArbitraje regulado por la Ley de Arbitraje (2003), basada en la Ley Modelo UNCITRAL.\n\nCentros principales: JCAA (Japan Commercial Arbitration Association).\n\nAlta confianza en procesos rápidos y neutrales.',
  },
  {
    continent: 'Asia',
    country: 'Corea del Sur',
    city: 'KR',
    strengths:
      'Cadena logística moderna, consumidores exigentes y alto poder adquisitivo; fuerte capacidad de procesamiento y retail (concentración de importadores/retailers). \nfas.usda.gov\n\nRegulador activo (MFDS) con normativas claras para alimentos importados.',
    weaknesses:
      'Requisitos de etiquetado en coreano y normas técnicas específicas (aditivos, listas permitidas), trámites de registro pueden ser exigentes. Dependencia de importaciones y sensibilidad a la protección del agricultor local en ciertos productos.',
    suppliers:
      'Empresas y cooperativas locales que actúan como importadores/distribuidores; además existen clusters de procesadores (ej. empresas de alimentos transformados). Directorios sectoriales (Kompass, KOTRA) listan importadores relevantes.',
    contractType:
      'Contratos de compraventa con especificaciones y contratación agrícola (contratos de suministro/forward contracts) gestionados por cooperativas y procesadores; en compras públicas/proveeduría se usan contratos tipo fijo/unit price (según normativa pública).',
    quality:
      'Autoridad principal: MFDS (Ministry of Food and Drug Safety). Estándares locales y requerimientos: HACCP, requisitos de aditivos, normas de contacto con alimentos, etiquetado en coreano. Certificaciones ISO 22000, FSSC también usadas por exportadores.',
    arbitration:
      'Firmante de la Convención de Nueva York.\n\nArbitraje administrado por el Korean Commercial Arbitration Board (KCAB).\n\nFuerte apoyo gubernamental a la resolución alternativa de disputas.\n\nProcedimientos eficientes y con uso frecuente de inglés.',
  },
  {
    continent: 'Oceania',
    country: 'Nueva Zelanda (Isla Norte)',
    city: 'NZ',
    strengths:
      'Infraestructura agrícola muy desarrollada (horticultura, kiwifruit, manzana, verduras, además de actividad lechera intensiva), fuerte reputación de calidad y trazabilidad. Buen acceso a puertos y exportadores consolidados.',
    weaknesses:
      'Distancias internas para ciertos productores; costos logísticos internos; normas fitosanitarias y bioseguridad estrictas (NZ es muy exigente con bioseguridad). Competencia fuerte en productos lácteos y hortícolas de alta calidad.',
    suppliers:
      'Pāmu (Landcorp) con operaciones en North Island, cooperativas y empresas hortícolas alrededor de Auckland, Bay of Plenty (kiwi), Hawke’s Bay (fruta), Waikato (dairy). Plataformas como PGG Wrightson son proveedores de insumos.',
    contractType:
      'Contratos de suministro lechero (supply agreements between farms and processors), acuerdos de contrato hortícola con especificaciones (calibre, brix, fecha), y contratos de servicio con cooperativas. Contratos suelen ser escritos y con estándares de calidad y auditoría.',
    quality:
      'Alto uso de HACCP/ISO 22000 en industrias procesadoras; fuerte cumplimiento de bioseguridad del MPI (Ministry for Primary Industries) — requisitos fitosanitarios y de exportación estrictos.',
    arbitration:
      'Adhiere a la Convención de Nueva York y a la Ley Modelo UNCITRAL.\n\nArbitraje regido por la Arbitration Act 1996.\n\nInstitución clave: New Zealand International Arbitration Centre (NZIAC).\n\nEnfoque en mediación previa y decisiones vinculantes y transparentes.',
  },
  {
    continent: 'Asia',
    country: 'Indonesia',
    city: 'IDN',
    strengths:
      'Gran oferta agrícola (aceite de palma, café, cacao, coco, frutas, especias, productos hortícolas, proteína animal) y capacidad exportadora grande — proveedores con experiencia internacional. Amplia oferta de insumos (fertilizantes nacionales).',
    weaknesses:
      'Variabilidad de calidad entre proveedores; problemas logísticos internos (islas múltiples), controles fitosanitarios variables según región, y necesidad de cumplir requisitos de certificación (p. ej. sostenibilidad para aceite de palma).',
    suppliers:
      'Grandes grupos y empresas: Wilmar (opera en Indonesia), Sinar Mas Group (agronegocios), Japfa, Astra Agro Lestari, grandes productores de palma, cooperativas de café/cacao, y empresas exportadoras como Great Giant Foods en horticultura/PI. Hay también fuertes empresas de insumos (PT Pupuk Indonesia en fertilizantes).',
    contractType:
      'Contratos de compraventa internacional (FOB/CIF), acuerdos de suministro a largo plazo para commodities (contratos por volumen), y contract farming en sectores como palma e integraciones verticales por grandes grupos. También uso frecuente de L/C para pagos.',
    quality:
      'Autoridades: BPOM (alimentos procesados/seguridad), estándares nacionales SNI (Standar Nasional Indonesia) y certificaciones internacionales (ISO 22000, HACCP) y certificaciones sectoriales (RSPO para aceite de palma). Halal (MUI) es clave para exportación e importación en países musulmanes.',
    arbitration:
      'Ratificó la Convención de Nueva York en 1981.\n\nArbitraje regulado por la Ley N° 30/1999.\n\nPrincipal centro: BANI (Badan Arbitrase Nasional Indonesia).\n\nLos laudos extranjeros deben ser reconocidos por la Corte Suprema, proceso algo lento.',
  },
];
